### ISSUE TITLE
[Feature Request]: Can we have Material type themes

### ISSUE THREAD

**Issue by Fungusware** [Krypton-Suite/Standard-Toolkit#1836] opened 2024-11-05 09:59 UTC
Is is feasable that the Krypton Toolkit could be styled to have a flat / material type theme?

I love the toolkit but it is looking a little bit dated, a super modern theme would make a huge difference.

**Comment by PWagner1** [comment] 2024-11-05 16:08
@Smurf-IV & @giduac 

I think this is more of a feature request, rather than a question?

cc. @Fungusware

**Comment by Smurf-IV** [comment] 2024-11-08 13:33
Duplicate of:
#114
and #1022

**Comment by PWagner1** [comment] 2024-11-08 17:45
Duplicate, closing

**Closed by PWagner1** 2024-11-08 17:45 UTC
Labels: duplicate, enhancement, new feature, suggestion, area:themes
