### ISSUE TITLE
[Bug]: No support for the 'help' button

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#219] opened 2021-07-30 17:48 UTC
**Describe the bug**
Krypton works with the close, maximise/restore and minimise buttons, _but_ not with the `help` button.

**Comment by Smurf-IV** [comment] 2021-07-31 08:58
Duplicate of #95

**Comment by Smurf-IV** [comment] 2021-07-31 08:59
And the Bug from the "Old" system about the help button in MessageBoxes has not been transferred over either..

**Comment by Smurf-IV** [comment] 2021-08-08 07:08
Seem like the Help button has never been implemented:
![image](https://user-images.githubusercontent.com/2418812/128624026-94abdbfd-c36a-49ad-8f8c-4da57acf7ec7.png)

**Comment by Smurf-IV** [comment] 2021-08-08 07:20
There are some "Rules" for when the "Help Form Button" is suppose to appear:
- The Help icon is only there when `HelpButton = True` and `MaximizeBox` and `MinimizeBox` are both set to False. This is the windows standard.
- You must change `FormBorderStyle` to `FixedDialog`. To benefit help functionality use `_HelpButtonClicked` event in form

https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-display-pop-up-help?view=netframeworkdesktop-4.8

I think this is way too restrictive, and if you want to add help, it could be done by a standard button spec:
![image](https://user-images.githubusercontent.com/2418812/128624250-599296e5-48a6-4d0a-9898-a280fe7767c7.png)

BUT, the button spec does not have a "Help" type.

So this is what I'll add.

Thoughts ?

**Comment by Wagnerp** [comment] 2021-08-08 07:25
It's definitely too restrictive, but why would a KForm need a pin type?

**Comment by Smurf-IV** [comment] 2021-08-08 07:27
It was just a demo of the type of Icons that are available for the ButtonSpec. 
"It" does not know where it is being used.
And why not, if you have a modeless form, and then you want to prevent it moving, then that could work, 
but It could normally be used  for MDI Forms, or freezing splitter, etc.

**Comment by Smurf-IV** [comment] 2021-08-08 07:46
Argghh.. Darn theme supported button images !

**Comment by Wagnerp** [comment] 2021-08-08 07:51
> Argghh.. Darn theme supported button images !

I know this may sound crazy, but I may be able to create new sprites if that would help?

**Comment by Wagnerp** [comment] 2021-08-08 07:53
Or try to figure out the colours

**Comment by Wagnerp** [comment] 2021-08-08 07:56
![image](https://user-images.githubusercontent.com/949607/128625148-244c0cbb-c542-4259-8bc6-d51817c69941.png)

**Comment by Smurf-IV** [comment] 2021-08-08 07:56
If it's easy and quick..
There's three per "Theme"
e.g. for the `Max`:
        private static readonly Image _blackMaxA = Resources.BlackButtonMaxA;
        private static readonly Image _blackMaxAH = Resources.BlackButtonMaxAH;
        private static readonly Image _blackMaxI = Resources.BlackButtonMaxI;

So will need the equivalent for the `Help`

**Comment by Wagnerp** [comment] 2021-08-08 08:03
The issue is that the size is irregular, or alternatively, completely redo all of them?

**Comment by Wagnerp** [comment] 2021-08-08 08:04
As you have blocky colours

**Comment by Wagnerp** [comment] 2021-08-08 08:05
![image](https://user-images.githubusercontent.com/949607/128625402-52ae2fc0-6957-4ba1-83ab-567cf305ad0c.png)

**Comment by Smurf-IV** [comment] 2021-08-08 08:13
> The issue is that the size is irregular, or alternatively, completely redo all of them?

The size should be consistent, as they have to fit into a certain area (i.e. the form bar) 16x16
Your choice.

> As you have blocky colours

I do? Not me ;-)

> pic

Well they could all be made consistent, and then let the drawing code actually resize them as needed (i.e. for Comboboxes, etc.)
![image](https://user-images.githubusercontent.com/2418812/128625626-16bc4660-1900-422e-b023-33b039484e35.png)
![image](https://user-images.githubusercontent.com/2418812/128625647-56fa9ba9-9c56-4a19-8e41-cc08e0000e95.png)

**Comment by Wagnerp** [comment] 2021-08-08 08:18
I kind of forgot, PowerToys colour picker to the rescue!

**Comment by Wagnerp** [comment] 2021-08-08 08:20
![image](https://user-images.githubusercontent.com/949607/128625847-08c86598-3811-4e9f-8802-9af725fcfdda.png)

**Comment by Wagnerp** [comment] 2021-08-08 08:29
![2010ButtonMDIHelpBlack](https://user-images.githubusercontent.com/949607/128626010-6bbae55b-b6f6-4872-a823-89bb8562e744.png)

Let me know what you think. I can't get it exact

**Comment by Smurf-IV** [comment] 2021-08-08 08:43
I think it needs to be sharper..
Where did you get the source from ?
Also.. Older "Help" icons used to be a "crap" so that needs to be in the older ones (Unless you have office 2007 running on Windows 7 / XP - I can do that !)

![image](https://user-images.githubusercontent.com/2418812/128626372-8ea0ac3c-3268-4dc4-be7f-78493cf9cf48.png)

**Comment by Wagnerp** [comment] 2021-08-08 08:48
> I think it needs to be sharper..
> Where did you get the source from ?
> Also.. Older "Help" icons used to be a "crap" so that needs to be in the older ones (Unless you have office 2007 running on Windows 7 / XP - I can do that !)
> 
> ![image](https://user-images.githubusercontent.com/2418812/128626372-8ea0ac3c-3268-4dc4-be7f-78493cf9cf48.png)

If you can, that would be great! I don't know if these icons were taken from the office suites themselves?

**Comment by Smurf-IV** [comment] 2021-08-08 09:00
Ok, Give me a while whilst I Create some VM's and then install the different "Offices"

**Comment by Smurf-IV** [comment] 2021-08-08 09:47
I forgot how small default xp was ...
![image](https://user-images.githubusercontent.com/2418812/128627883-0a1a3e6a-c43d-4183-bcfc-412755220c52.png)

**Comment by Wagnerp** [comment] 2021-08-08 09:58
I do have a pre-made XP VM, but I wouldn't know where to look in the Office 2003 files

**Comment by Smurf-IV** [comment] 2021-08-08 10:01
There is not a krypton theme for 2003 ??
And I was just going to "Grab" the image from the form bar.

**Comment by Wagnerp** [comment] 2021-08-08 10:04
![image](https://user-images.githubusercontent.com/949607/128628285-0299bb71-9083-421b-a0bf-272cb81848f3.png)

**Comment by Smurf-IV** [comment] 2021-08-08 10:05
So there is.. I hadn't scrolled far enough :-(

**Comment by Wagnerp** [comment] 2021-08-08 10:05
But... this only really works pre Vista (I think)

**Comment by Smurf-IV** [comment] 2021-08-08 10:07
I can install
Office2k3, 2k7, 2k10, 2k13, 2k16 (Maybe), 2k19 (Although this is really 2k16 with fixes), Office 365 (Maybe)
Onto XP, win7, win10

**Comment by Wagnerp** [comment] 2021-08-08 10:14
Office 2k22 is still broken, got a colour identity crisis

**Comment by DarthVader85PA** [comment] 2021-08-08 10:42
Hey @Wagnerp , @Smurf-IV 

Thanks a lot! You both are the best!
On the Form-Button-Specs I don't thought. But you will create help button, that's very fine!

Greetings from Germany!
Danny

**Comment by Smurf-IV** [comment] 2021-08-08 12:46
What is the Office2k3 theme supposed to be doing over the System ?
![image](https://user-images.githubusercontent.com/2418812/128632282-6d677b8e-3605-482a-99c2-0b874ef46e30.png)

i.e. isn't it just the System Theme ?

**Comment by Wagnerp** [comment] 2021-08-09 07:43
Now this is just ridiculous!

```cs
  private static readonly Image _blackCloseA = Resources.BlackButtonCloseA;
        private static readonly Image _blackCloseAH = Resources.BlackButtonCloseAH;
        private static readonly Image _blackCloseI = Resources.BlackButtonCloseI;
        private static readonly Image _blackMaxA = Resources.BlackButtonMaxA;
        private static readonly Image _blackMaxAH = Resources.BlackButtonMaxAH;
        private static readonly Image _blackMaxI = Resources.BlackButtonMaxI;
        private static readonly Image _blackMinA = Resources.BlackButtonMinA;
        private static readonly Image _blackMinAH = Resources.BlackButtonMinAH;
        private static readonly Image _blackMinI = Resources.BlackButtonMinI;
        private static readonly Image _blackRestoreA = Resources.BlackButtonRestoreA;
        private static readonly Image _blackRestoreAH = Resources.BlackButtonRestoreAH;
        private static readonly Image _blackRestoreI = Resources.BlackButtonRestoreI;
```

**Comment by Wagnerp** [comment] 2021-08-09 07:46
Plus you have duplicates in `Resources.resx`... WTF!

**Comment by Smurf-IV** [comment] 2021-08-09 14:29
`Resources.resx` is generated from the source bitmaps. That's how they get into the binary, and then are available to the code via `Resources.####` like you have shown above.

**Comment by Wagnerp** [comment] 2021-08-09 15:01
I'm on the case, though it may take several days to sort it out #256

**Comment by Smurf-IV** [comment] 2021-08-09 16:24
Ok.. Can these be separate then because I'm just waiting for the images?
Or do you want me to push the changes and then you fix the Palette usages ?

**Comment by Wagnerp** [comment] 2021-08-09 16:27
> Ok.. Can these be separate then because I'm just waiting for the images?
> Or do you want me to push the changes and then you fix the Palette usages ?

I'm creating separate resource files O2k7 was easy, but O2k10... well...

**Comment by Wagnerp** [comment] 2021-08-09 16:28
![image](https://user-images.githubusercontent.com/949607/128740585-5f479b0c-c01e-4aab-b3c0-dd0ed555e762.png)

**Comment by Smurf-IV** [comment] 2021-08-09 16:30
I think all theme resources should have 3 each otherwise it does not make sense, as has been seen by the research into the Help Icon. The states do exist, they have just not been implemented in the themes correctly (As per the other bug about the disabled look of the minimise image!)

**Comment by Wagnerp** [comment] 2021-08-09 16:33
O2k7 progress so far...

![image](https://user-images.githubusercontent.com/949607/128741242-9186ba0c-7bfe-4424-ba8e-928377221e17.png)

**Comment by Wagnerp** [comment] 2021-08-09 16:35
![image](https://user-images.githubusercontent.com/949607/128741471-48956f1f-4bf3-4d05-a07a-400210eaf3ad.png)

**Comment by Smurf-IV** [comment] 2021-08-09 16:42
I would stick with bmp for these small files, as it gives better storage (i.e. it way smaller)

**Comment by Wagnerp** [comment] 2021-08-09 16:57
The radio button images might be harder to figure out

![image](https://user-images.githubusercontent.com/949607/128744473-da9e16d4-1c20-450c-93ea-b274ce2836d4.png)

**Comment by Wagnerp** [comment] 2021-08-11 08:48
@Smurf-IV As the icons can be 'recoloured', do you want me to use the disabled/normal/active colours from the palette for the 'help' images?

**Comment by Smurf-IV** [comment] 2021-08-11 17:00
Yes please i..e not programatic recolouring, as this leads to problems (Especially when dealing with dark themes)

**Comment by Wagnerp** [comment] 2021-08-11 17:03
> Yes please i..e not programatic recolouring, as this leads to problems (Especially when dealing with dark themes)

It won't be done in the code itself, just within iconizer website

**Closed** 2021-08-18 16:06 UTC
Labels: bug, completed
