### ISSUE TITLE
[Bug]: Todays Alpha MessageBox has "Selectable text" ??

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1659] opened 2024-07-20 11:03 UTC
![image](https://github.com/user-attachments/assets/81b88e19-7229-45f0-aa03-61130438fc1c)

Please check implementation in V85 as well

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-21 20:08
Yes, I noticed this since KTextBox was used to display the message and I assumed this was intended.

If this is not the desired behavior (I personally don't like it but it's not that big of a deal for me), there are a couple of potential fixes I can think of:

- Make the text box disabled instead of read-only and adjust its style to "look normal".
- Disable the textbox's focus entirely (this can be done by sending a `WM_KILLFOCUS` message instead of `WM_SETFOCUS` in `WndProc`).

**Comment by Wagnerp** [comment] 2024-07-22 07:04
> Yes, I noticed this since KTextBox was used to display the message and I assumed this was intended.
> 
> If this is not the desired behavior (I personally don't like it but it's not that big of a deal for me), there are a couple of potential fixes I can think of:
> 
> * Make the text box disabled instead of read-only and adjust its style to "look normal".
> * Or better: Disable the textbox's focus entirely (this can be done by sending a `WM_KILLFOCUS` message instead of `WM_SETFOCUS` in `WndProc`). But we'll need to use a custom KTextBox for that.

My vote goes to a custom KTextBox

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-22 07:14
Hi @Wagnerp

I can take care of that, but I'm not sure where to put it. Maybe in the General folder (as an `internal` type, of course)?

**Comment by giduac** [comment] 2024-07-22 07:17
@Ahmed-Abdelhameed 
If I'm right the handle to the textbox is available from the messagebox for.
Can't you do a SendMessage to that from the form constructor ?

**Comment by Wagnerp** [comment] 2024-07-22 07:21
> Hi @Wagnerp
> 
> I can take care of that, but I'm not sure where to put it. Maybe in the General folder (as an `internal` type, of course)?

Hi @Ahmed-Abdelhameed 

If I recall, I think that I've made a few internal controls in the 'General' folder

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-22 07:22
@giduac 

We need to intercept the `WM_SETFOCUS` message in `WndProc` of the KTextBox. This is done on the fly, not a flag that can be set at the beginning. There might be a better way but that's the best I could think of.

**Comment by giduac** [comment] 2024-07-22 07:23
@Ahmed-Abdelhameed 
Or attach a NativeWindow to the control .
Add a wndproc and intercept / eat the message there ?

**Comment by giduac** [comment] 2024-07-22 07:26
For example:

```cs
    public class TableLayoutPanel : NativeWindow
    {

        /*
         * Tweaks the position of panel outside the normally possible area via Top and left properties
         * Derived from:
         * https://stackoverflow.com/questions/2567172/c-sharp-tabcontrol-border-controls
         */

        protected override void WndProc( ref Message m )
        {

            if ( m.Msg == WindowsConstants.WM_WINDOWPOSCHANGING ) {

				WindowsStructures.WINDOWPOS w = (WindowsStructures.WINDOWPOS)m.GetLParam( typeof( WindowsStructures.WINDOWPOS ) );

                //left
                w.x -= 2;
                //top
                w.y -= 0;
                //width
                w.cx += 0;
                //height
                w.cy += 0;

                Marshal.StructureToPtr( w, m.LParam, true );

            }

            base.WndProc( ref m );

        }

    }
```

**Comment by giduac** [comment] 2024-07-22 07:39
@Ahmed-Abdelhameed 
Also a thing to consider is that KTextBox is a dropin replacement for WinForms textbox.
So if Winform textbox does not allow for selectable text KTextbox shouldn't too.

That would make this a bug just like not handling \n or \r like Winforms does.

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-22 08:14
@giduac 

Actually, it's quite the opposite. WinForm's TextBox allows selecting text, of course. That's why this would be a _custom_ KTextBox (as opposed to applying the changes to KTextBox itself). It would be something like this:

```
internal class UnselectableKTextBox : KryptonTextBox
{
    UnselectableKTextBox()
    {
        SetStyle(ControlStyles.Selectable, false);
    }

    const int WM_SETFOCUS = 0x0007;
    const int WM_KILLFOCUS = 0x0008;

    protected override void WndProc(ref Message m)
    {
        if (m.Msg == WM_SETFOCUS)
        {
            m.Msg = WM_KILLFOCUS;
        }
        base.WndProc(ref m);
    }
}
```

In any case, I just tried this and althought it did work with custom TextBox, it won't be easy getting the same behavior from a custom KTextBox because it uses another TextBox internally.

So, that leaves us with the disabled KTextBox option. Something like this in the VisualMessageBoxForm's constructor should do the trick:

```
var paletteContent = ktextBoxMessageText.StateDisabled.Content;
paletteContent.Color1 = paletteContent.GetContentShortTextColor1(PaletteState.Normal);
paletteContent.Font = paletteContent.GetContentShortTextFont(PaletteState.Normal);
paletteContent.Padding = paletteContent.GetContentPadding(PaletteState.Normal);
```

CC: @Wagnerp & @Smurf-IV What do you think?

That's, of course, unless you want to go back to using a label instead of a text box (which is what I prefer, tbh 😅).

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-22 08:15
> For example:
> 
> ```cs
>     public class TableLayoutPanel : NativeWindow
>     {
> 
>         /*
>          * Tweaks the position of panel outside the normally possible area via Top and left properties
>          * Derived from:
>          * https://stackoverflow.com/questions/2567172/c-sharp-tabcontrol-border-controls
>          */
> 
>         protected override void WndProc( ref Message m )
>         {
> 
>             if ( m.Msg == WindowsConstants.WM_WINDOWPOSCHANGING ) {
> 
> 		WindowsStructures.WINDOWPOS w = 
> 		       (WindowsStructures.WINDOWPOS)m.GetLParam( typeof( WindowsStructures.WINDOWPOS ) );
> 
>                 //left
>                 w.x -= 2;
>                 //top
>                 w.y -= 0;
>                 //width
>                 w.cx += 0;
>                 //height
>                 w.cy += 0;
> 
>                 Marshal.StructureToPtr( w, m.LParam, true );
> 
>             }
> 
>             base.WndProc( ref m );
> 
>         }
> 
>     }
> ```

I'm not sure I understand this one. Is this related to preventing text selection?

**Comment by giduac** [comment] 2024-07-22 08:36
@Ahmed-Abdelhameed 
Actually the KMB for internaltextbox class already has its own wndproc in there:
Adding your code to the switch statement does work:
```cs
protected override void WndProc(ref Message m)
{
	switch (m.Msg)
	{
		case WM_SETFOCUS:
			m.Msg = WM_KILLFOCUS;
			base.WndProc(ref m);
			break;
		case PI.WM_.NCHITTEST:
		. . .
```

When the mouse moves over the text the cursor changes to the edit text cursor...

**Comment by giduac** [comment] 2024-07-22 09:46
@Ahmed-Abdelhameed 
The earlier message about the wndproc was incorrect and I've taken that out.

Did a test with a NativeWindow on the KMB

This is the custom native window class private to the KMB form

```cs
    internal partial class VisualMessageBoxForm : KryptonForm
    {
        private class NativeTextBox : NativeWindow
        {
            private const int WM_SETFOCUS = 0x0007;
            private const int WM_KILLFOCUS = 0x0008;

            protected override void WndProc(ref Message m)
            {
                if (m.Msg == WM_SETFOCUS)
                {
                    m.Msg = WM_KILLFOCUS;
                }
                base.WndProc(ref m);
            }
        }
```
Instance goes here:
```cs
        #region Instance Fields
        private NativeTextBox _nativeTextBox = new NativeTextBox();
```
Assignment of the handle takes place in the custom constructor
```cs
        internal VisualMessageBoxForm(IWin32Window? showOwner, string? text, string? caption,
                                       KryptonMessageBoxButtons buttons,
                                       KryptonMessageBoxIcon icon,
                                       KryptonMessageBoxDefaultButton defaultButton,
                                       HelpInfo? helpInfo, bool? showCtrlCopy,
                                       bool? showHelpButton,
                                       bool? showCloseButton)
        {
            // Store incoming values
            _text = text;
            _caption = caption;
            _buttons = buttons;
            _kryptonMessageBoxIcon = icon;
            _defaultButton = defaultButton;
            _helpInfo = helpInfo;
            _showOwner = showOwner;
            _showHelpButton = showHelpButton ?? (helpInfo != null);

            // Create the form contents
            InitializeComponent();
            _nativeTextBox.AssignHandle(ktextBoxMessageText.TextBox.Handle);
```

**Comment by giduac** [comment] 2024-07-22 09:49
But I think that we should explore if a solution with KWraplabel can be done.
Then we don't need to do tricks...

**Comment by Wagnerp** [comment] 2024-07-22 18:22
Hi @Ahmed-Abdelhameed 

On another note, are you on Discord if so can you DM me? Thanks :)

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-23 00:16
@giduac 

> But I think that we should explore if a solution with KWraplabel can be done. Then we don't need to do tricks...

I agree. A wrap label is more suitable for this, but we'll probably need to figure out a way to fix the tab char issue (although I don't think tab chars should be used in a MBox text but others do, apparently). Context [here](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1599#issuecomment-2210553067).

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-23 00:46
Hi @Wagnerp 

I don't really use Discord. Tried to create an account before and it asked me to verify my phone number, then proceeded to reject my phone number ¯\\\_(ツ)\_/¯

If you're using [Element](https://element.io/), you can DM me [@41686d6564](https://matrix.to/#/@41686d6564:matrix.org).

**Comment by giduac** [comment] 2024-07-23 06:23
> @giduac
> 
> > But I think that we should explore if a solution with KWraplabel can be done. Then we don't need to do tricks...
> 
> I agree. A wrap label is more suitable for this, but we'll probably need to figure out a way to fix the tab char issue (although I don't think tab chars should be used in a MBox text but others do, apparently). Context [here](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1599#issuecomment-2210553067).

Hi @Ahmed-Abdelhameed,

The tab char has been handled/added through this ticket: https://github.com/Krypton-Suite/Standard-Toolkit/issues/1424
KWraplabel has problens with /t.

KLabel handles /n /rn and /t. 
That leaves /r to fix wich can be done through a replace like this:
```cs
kryptonLabel1.Text = Regex.Replace(kryptonLabel1.Text, "\r(?!\n)", "\n");
```

After testing this I would suggest Klabel as the first choice.

**Comment by Wagnerp** [comment] 2024-07-23 06:30
Hi @giduac & @Ahmed-Abdelhameed 

Should the recent comments be moved to #1660 to avoid confusion?

**Comment by giduac** [comment] 2024-07-23 06:31
> Hi @giduac & @Ahmed-Abdelhameed
> 
> Should the recent comments be moved to #1660 to avoid confusion?

Two birds with one stone...

**Comment by giduac** [comment] 2024-07-23 06:31
> Hi @giduac & @Ahmed-Abdelhameed
> 
> Should the recent comments be moved to #1660 to avoid confusion?

@Wagnerp 
Two birds with one stone...

**Comment by Wagnerp** [comment] 2024-07-23 06:36
> Could a KWraplabel be an option instead of KTB...?
That one also takes the right lines breaks

It already uses a KWraplabel **but** the dev needs to remember to put the relevant escape characters in the code. It could be a documentation thing.

**Comment by giduac** [comment] 2024-07-23 06:44
> > Could a KWraplabel be an option instead of KTB...?
> > That one also takes the right lines breaks
> 
> It already uses a KWraplabel **but** the dev needs to remember to put the relevant escape characters in the code. It could be a documentation thing.

It was a wraplabel before but now uses a KTextbox
![image](https://github.com/user-attachments/assets/f9256c8a-0a66-4687-b404-93d4ea520d5b)

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-25 08:03
Hi @giduac 

> The tab char has been handled/added through this ticket: https://github.com/Krypton-Suite/Standard-Toolkit/issues/1424

That ticket was resolved by replacing KWrapLabel with a KTextBox on the KMB form. AFAICT, KWrapLabel still does _not_ support tab characters.

**Comment by giduac** [comment] 2024-07-25 09:56
@Ahmed-Abdelhameed, @Smurf-IV & @Wagnerp 

I tried all four Ktext controls including krichtextbox and they all have their perks in other words none is perfect.
We can try Winfroms counterparts.

Actually the KTextbox approach from Smurf works best of all in this scenario. And a little added string replace to support all line break types can be added. I like the fact that with a Ktextbox the text IS selectable, something missed with the standard MB.
So I really don't see a problem there.

And it has been done before by MS.... it's not a bug it's a feature... ;)
So why not follow that `concept`....

Your thoughts please so we can put this KMessageBox drama to bed....

**Comment by giduac** [comment] 2024-07-25 16:05
Just gave Winforms TextBox a try and that also is not straightforward

**Comment by Smurf-IV** [comment] 2024-07-26 06:40
> And it has been done before by MS.... it's not a bug... It's a feature.!!.. ;)
> So why not follow that concept....

Having it selectable, makes Auto readers etc confused.
It should be simple (once done) to make it readonly and **not** selectable, and **not** tabable

**Comment by giduac** [comment] 2024-07-26 06:58
@Smurf-IV 
Are there more specifics you can think that should be looked at / included so we get a complete picture of what needs to be done.

**Comment by giduac** [comment] 2024-07-27 07:44
Hi @Smurf-IV,  @Wagnerp & @Ahmed-Abdelhameed,

Looks like I found a solution. 
- `TextRenderer.MeasureText` has problems determining the correct length when a string contains \t char(s) (was found while testing controls), `Graphics.MeasureString` does not.
- `Graphics.MeasureString` has problems determining the correct height in general (was already known), `TextRenderer.MeasureText` does not. 
- Combining the correct results of both method gives the correct size for the control.
- I've changed the control to a KLabel, which fixes the selected text problem.
- All types of line breaks contained are replaced with ` System.Environment.NewLine`.
- The message text needs to end on a line break. So the text is checked and if it doesn't end with  System.Environment.NewLine` it is added.

I'd like everyone to test this using branch:
https://github.com/giduac/Standard-Toolkit/tree/1659-MessageBox-has-selectable-text

**Comment by Wagnerp** [comment] 2024-07-27 08:04
> Hi @Smurf-IV, @Wagnerp & @Ahmed-Abdelhameed,
> 
> Looks like I found a solution.
> 
> * `TextRenderer.MeasureText` has problems determining the correct length when a string contains \t char(s) (was found while testing controls), `Graphics.MeasureString` does not.
> * `Graphics.MeasureString` has problems determining the correct height in general (was already known), `TextRenderer.MeasureText` does not.
> * Combining the correct results of both method gives the correct size for the control.
> * I've changed the control to a KLabel, which fixes the selected text problem.
> * All types of line breaks contained are replaced with ` System.Environment.NewLine`.
> * The message text needs to end on a line break. So the text is checked and if it doesn't end with  System.Environment.NewLine` it is added.
> 
> I'd like everyone to test this using branch: https://github.com/giduac/Standard-Toolkit/tree/1659-MessageBox-has-selectable-text

Can confirm that this works :)

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-29 03:06
Hi @giduac 

Great work fixing the linebreak issues!

The part about `\t` and measuring text is inaccurate though. For example, try to test with this code and it will start breaking after line 10:

```cs
for (int max = 1; max <= 20; max++)
{
    var lines = Enumerable.Range(1, max).Select(i => $"This is line #{i}.\tThis is line #{i}.").ToList();
    string joined = string.Join("\r\n", lines);
    KryptonMessageBox.Show(joined, $"NumOfLines={max}", KryptonMessageBoxButtons.OK, KryptonMessageBoxIcon.Information);
}
```

I don't think using `Graphics.MeasureString()` is the answer here. The golden rule is if you use `Graphics.MeasureString()` to measure the text, then you have to use `Graphics.DrawString()` to draw it. Similarly, `TextRenderer.MeasureText()` pairs with `TextRenderer.DrawText()`. In other words, either GDI+ for both or GDI for both, but you can't mix them.

To make `TextRenderer.MeasureText()` account for tab chars, we can pass `TextFormatFlags.ExpandTabs` to it. But I tried that and it's still not 100% accurate. I will investigate this a little bit more later today.

**Comment by giduac** [comment] 2024-07-29 06:05
> . The golden rule is if you use `Graphics.MeasureString()` to measure the text, then you have to use `Graphics.DrawString()` to draw it. Similarly, `TextRenderer.MeasureText()` pairs with `TextRenderer.DrawText()`. In othe

@Ahmed-Abdelhameed 
Well it seems to work as expected when using the measurements from MeasureText and drawing the text on a bitmap. When that's displayed in a KPictureBox it show the text as it should. See the snippet.

It means that we're doing it correct and these functions work correctly. 
That leaves the text formatting of the control to be the problem as this is not on par with the way MeasureText does. 

```cs
        private void kbtnTestText_Click(object sender, EventArgs e)
        {
            //krtbMessageBody.Text = SEED_TEXT;
            var lines = Enumerable.Range(1, 40).Select(i => $"This is line #{i}.\tThis is line #{i}.").ToList();
            string joined = string.Join("\r", lines);

            SizeF sizeF = TextRenderer.MeasureText(joined, krtbMessageBody.Font, new Size(1000, 1000), TextFormatFlags.ExpandTabs);
            Size size = new((int)Math.Ceiling(sizeF.Width), (int)Math.Ceiling(sizeF.Height));

            Bitmap b = new(size.Width, size.Height);
            Graphics g = Graphics.FromImage(b);

            g.FillRectangle(new SolidBrush(Color.White), new Rectangle(0, 0, size.Width, size.Height));
            TextRenderer.DrawText(g, joined, krtbMessageBody.Font, new Point(0, 0), Color.Black, Color.White);

            kryptonPictureBox1.Image = b;
        }
```

**Comment by giduac** [comment] 2024-07-29 11:40
@Ahmed-Abdelhameed 
Did a little more testing and found that `KLabel `with `AutoSize `set to `True` does a very good job calculating it's size on it's own.

On the left is the custom drawn text in the picture box from above here. 
On the right the KLabel with autosize enabled. 
It show that KLabel applies a line spacing different from `DrawText`....

![image](https://github.com/user-attachments/assets/7a50438d-80a4-48cb-a9d0-ac16ed0964d6)

So the cell in the TableLayoutPanel that the Label is in should be set so it can expand.

**Comment by giduac** [comment] 2024-07-29 16:57
Did some more fiddling. 
To be fully in control we need to know how the control (KLabel) measures the string....

**Comment by giduac** [comment] 2024-07-31 13:05
@Ahmed-Abdelhameed,

And a bit more.
It's definitely coming from the control. The KLabel paints the text with a slightly larger line spacing. This screenshot is with font size 9. The part in from is the screenshot from the label and in the back from DrawText.

![image](https://github.com/user-attachments/assets/ba1a7298-4c61-4737-8aca-1573bc48bb20)

**Comment by Smurf-IV** [comment] 2024-08-01 06:40
> Or be able to make use of the AutoSize ability of KLabel itself....

Might be the easiest.

**Comment by giduac** [comment] 2024-08-01 07:18
> > Or be able to make use of the AutoSize ability of KLabel itself....
> 
> Might be the easiest.
@Smurf-IV & @Ahmed-Abdelhameed 

Already had a go at that in the current setting / tablelayout approach.
Attached to a form the label just resizes out of the form bounds and that would be good. The form has to be visible for that, the label not.

With the KLabel inside the cell it is (probably ) hampered by the tablelayoutpanel. Also with the Label's docking set to none or top (not fill). Adding  a klabel to the KMB form didn't work, probably due the docked tablelayoutpanel.

Currently looking into the Winapi how it's done there. 
<https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-gettextextentpoint32w>
<https://learn.microsoft.com/en-us/windows/win32/gdi/drawing-text-from-different-fonts-on-the-same-line>
<https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-selectobject>
<https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createfonta>

**Comment by giduac** [comment] 2024-08-01 09:19
> > Or be able to make use of the AutoSize ability of KLabel itself....
> 
> Might be the easiest.

@Smurf-IV 
If you explore that option while we look into the others ?

**Comment by giduac** [comment] 2024-08-02 09:06
Hi @Smurf-IV, @w, & @Ahmed-Abdelhameed,

A KRichTextBox approach that is working here.

Please test extensively.....and let's hear it....

**Comment by giduac** [comment] 2024-08-02 10:10
Disabled Zoom on the KRTB and added a handler that releases the handle from the native window.
Update the branch if needed...

**Comment by Smurf-IV** [comment] 2024-08-03 09:39
> A KRichTextBox approach that is working here. Test Branch: https://github.com/giduac/Standard-Toolkit/tree/1659-MessageBox-has-selectable-text Please test extensively.....and let's hear it....

It's still "Over calculating" the height when using the "Lot's of lines" example text.
But it appears to be solid otherwise ;-)

**Comment by giduac** [comment] 2024-08-03 10:05
@Smurf-IV 

A picture perfect solution is not in it, imo. This is pretty close.
The autosize label approach is also a possible one. But needs a bit of trickery...

Found a couple of other things that need a look.
If the text can be centered vertically that would make up for the excess height.

**Comment by giduac** [comment] 2024-08-03 10:11
Like said earlier, to formulate some limitations wherein this operates.
It's a dialog to display simple messages and not a spreadsheet app.
As you can see in the Testform big text sample we are doing a better job than the standard MB.

**Comment by giduac** [comment] 2024-08-03 19:33
@Smurf-IV , @Ahmed-Abdelhameed , & @Wagnerp 

The border is on, to show how much excess height there is.
Vertical alignment of the text within the KRTB is not possible. 
This is a passable solution and will proceed with implementing.

![image](https://github.com/user-attachments/assets/fe9144d2-b4d5-455b-bd43-3a9d0964283e)

**Closed** 2024-08-05 07:17 UTC
Labels: bug, fixed, regression, area:toolkit, version:85, version:90
