### ISSUE TITLE
[Feature Request]: KryptonDomainUpDown has no AutoSize property

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#668] opened 2022-03-10 13:08 UTC
Is your feature request related to a problem? Please describe.
KryptonDomainUpDown has no AutoSize property. The standard Winforms equivalent has.

Describe the solution you'd like
Please, make the property available like in the standard control.

Additional context
Sizing the property by hand/mouse in the designer is possible though.

**Comment by Wagnerp** [comment] 2022-03-10 17:31
Duplicate of #667 - Closing

**Closed by Wagnerp** 2022-03-10 17:31 UTC
Labels: enhancement, new feature, suggestion

**Comment by giduac** [comment] 2022-03-10 18:00
@Wagnerp 
This one is for a **Domain** updown and 667 is for a **Numeric** updown.
The requests  are slightly different...

**Comment by Wagnerp** [comment] 2022-03-10 18:12
> @Wagnerp This one is for a **Domain** updown and 667 is for a **Numeric** updown. The requests are slightly different...

@giduac Might be better to merge the 2 into 1 request though?
