### ISSUE TITLE
[Bug]: After a designer "Reset click" on the `CornerRoundingRadius`, it is still showing as a modified value, and still being written out into the designer file

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#916] opened 2023-01-21 11:20 UTC
Using todays alpha branches

found via #915

![image](https://user-images.githubusercontent.com/2418812/213864677-66582ce4-c912-44ef-b7ce-102412c68f54.png)

**Comment by Wagnerp** [comment] 2023-01-31 10:59
Fixed :)

![image](https://user-images.githubusercontent.com/949607/215742234-28c30f2d-58a4-4c4e-9d33-488ae49697be.png)

**Comment by Wagnerp** [comment] 2023-02-02 17:50
Duplicate of #877

**Comment by Wagnerp** [comment] 2023-02-03 08:05
Resolved 03/02/2023

**Closed by Wagnerp** 2023-02-03 08:05 UTC
Labels: bug, duplicate, fixed, designer
