### ISSUE TITLE
[Bug]: Unable to adjust height of KryptonForm when KryptonRibbon is added

### ISSUE THREAD

**Issue by Ptkatz** [Krypton-Suite/Standard-Toolkit#1174] opened 2023-11-14 10:18 UTC
Krypton Versin: Stable 80.23.11.318

https://github.com/Krypton-Suite/Standard-Toolkit/assets/112046443/8198f971-86e9-4990-8053-f881b36e4256

**Comment by Wagnerp** [comment] 2023-11-14 10:44
@Smurf-IV Could this be caused by #1117?

**Comment by AngeloCresta** [comment] 2023-11-14 19:24
Hi, no the error is in VisualForm.cs (D:\Projects\_Comp\Krypton\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Visuals\VisualForm.cs)

where is looping here:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/12256319/805034e9-f657-4c79-8b98-ccc6dc096045)

in fact if you just comment out the lines everthing will work again (all ribbon's examples are affected).

Hope this helps
Angelo

**Comment by Wagnerp** [comment] 2023-11-15 08:00
Hi @AngeloCresta 

Thanks, it was caused by #1117. Will include a temporary fix in an upcoming patch.

**Comment by Wagnerp** [comment] 2023-11-17 10:57
Hi @Ptkatz & @AngeloCresta 

This has now been fixed in build 321

**Comment by Ptkatz** [comment] 2023-11-17 12:15
Okay, I'll try it. Thank you : )

**Closed** 2023-11-18 07:06 UTC
Labels: bug, fixed
