### ISSUE TITLE
[Bug]: KForm has a thin magenta border after the fix of #1749

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Standard-Toolkit#1757] opened 2024-08-29 12:28 UTC
**Describe the bug**
See #1749 for extended information.
Since this has been fixed KForm has a thin magenta border.
Only when the border width is set to 0 the border is not visible.

**To Reproduce**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Framework/.NET Version: current alpha

**Additional context**
N/A

**Comment by PWagner1** [comment] 2024-09-01 14:46
Hi @giduac 

What happens if you set it to transparent?

**Comment by Smurf-IV** [comment] 2024-09-02 06:16
> Hi @giduac
> 
> What happens if you set it to transparent?

It should already be "Transparent" from the change that I made, so is something resetting it to a different colour ?

**Comment by Smurf-IV** [comment] 2024-09-08 07:10
> > Hi @giduac
> > What happens if you set it to transparent?
> 
> It should already be "Transparent" from the change that I made, so is something resetting it to a different colour ?

FYI:
The transparency no longer applies, because this is a 0.5 pixel offset, therefore the colour is slightly merged with the border, thus not making it "Pure" magenta" anymore !
Then due to HDpi monitors and scaling, it makes it appear to be a single pixel border added to the Form Non-Calc region(s)
This is mainly caused by the introduction of the `float` rounding, and the fallout of using `float` calculations for borders that are drawn into `int` regions. It was fine until windows started to respect half-pixels, and then scaled them !!

**Comment by giduac** [comment] 2024-09-08 07:40
> > > Hi @giduac
> > > What happens if you set it to transparent?
> > 
> > 
> > It should already be "Transparent" from the change that I made, so is something resetting it to a different colour ?
> 
> FYI: The transparency no longer applies, because this is a 0.5 pixel offset, therefore the colour is slightly merged with the border, thus not making it "Pure" magenta" anymore ! Then due to HDpi monitors and scaling, it makes it appear to be a single pixel border added to the Form Non-Calc region(s) This is mainly caused by the introduction of the `float` rounding, and the fallout of using `float` calculations for borders that are drawn into `int` regions. It was fine until windows started to respect half-pixels, and then scaled them !!

Then I would suggest to set the default border width for KForm States to zero as a part of this correction.

**Comment by giduac** [comment] 2024-09-09 06:56
@Smurf-IV 
This might be of interest:
https://reza-aghaei.com/panel-border-size-and-border-color-customize-nonclient-area/

**Comment by Smurf-IV** [comment] 2024-09-22 12:40
Sorry it took so long!
I was trying to make the minimum of changes and yet still get it to work in all the scenarios.

PR on it's way:
![image](https://github.com/user-attachments/assets/6bfc5625-eba9-48a5-90e3-646bb6473aa9)

**Closed** 2024-09-22 12:41 UTC
Labels: bug, under investigation, regression, version:90
