### ISSUE TITLE
[Bug]: KryptonComboBox steals the focus using keydown event to jump between controls with enter key in a form

### ISSUE THREAD

**Issue by almendieta** [Krypton-Suite/Standard-Toolkit#1400] opened 2024-04-13 20:15 UTC
**Describe the bug**
KryptonComboBox stoles the focus using keydown event to jumb between controls with enter key in a frm
**To Reproduce**
1. Create at least 5 kryptontextbox controls, include a kryptoncombobox, a kryptoncheckbox and paste this code in each control keydown event:
        If e.KeyCode = Keys.Enter Then
            e.SuppressKeyPress = True  ' Evita el sonido de "ding" cuando se presiona Enter
            Me.SelectNextControl(Me.ActiveControl, True, True, True, True)
        End If

2. If you try and press enter key, focus finish always in kryptoncombobox. 

**Expected behavior**
Not sure if there is any way to configure this control to avoid this behaviour, so pressing enter key focus jumps between controls based in tabindex property.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64b
 - Version:19042.631
 - Framework/.NET Version: [e.g. 4.8.1] 
 - Toolkit Version: 90.24.2.52

**Comment by lesandrog** [comment] 2024-04-15 11:43
Hello, I tried to reproduce, but your code worked normally, with version 80.24.3.64.
You can try replacing "Me.SelectNextControl(Me.ActiveControl, True, True, True, True)" with "SendKeys.Send("{TAB}")" or "KryptonTextBox1.Focus()"

**Comment by giduac** [comment] 2024-06-16 09:50
@almendieta 

I tried this approach with Krypton controls and Winforms controls.
Both have the same result (erratic behaviour) using your code.

Documentation on Control.SelectNextControl():
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.selectnextcontrol?view=windowsdesktop-8.0

The advise from @lesandrog above is a good starting point imo.
By using the normal tab-key and setting the tab index you would be using the standard way to switch controls. That would be my way to go about his.

As far as I can see this is not a bug in the Krypton Toolkit.

@Wagnerp please close this ticket as this is not a bug from our side.
Thanks.

**Closed** 2024-06-16 12:53 UTC
Labels: bug, answered, awaiting feedback
