### ISSUE TITLE
[Bug]: Use of `Image.Equals` does not do what you expect, and results in a noisy Designer file

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1632] opened 2024-07-13 14:42 UTC
When performing the following code:
![image](https://github.com/user-attachments/assets/17e1d526-1a74-453a-9fb8-3c83372c867c)

Every image will return false, because an `Image` class does not override the `Equality operator`
https://stackoverflow.com/questions/6412778/comparing-images

Therefore, if using a Toolbar in the designer, you will get "Every Image" also stored, even tho it has not been overridden:
![image](https://github.com/user-attachments/assets/56c2117c-3c4c-40c9-80c7-fa9a53c3d96f)

**Comment by Smurf-IV** [comment] 2024-07-13 14:43
Please also check every usage in the following:
![image](https://github.com/user-attachments/assets/3fedda0f-9f8c-4c0e-af57-2f0e251ed30b)

**Comment by giduac** [comment] 2024-07-17 06:04
Hi @Wagnerp,

Do you have time for this one?

**Comment by Wagnerp** [comment] 2024-07-17 07:29
> Hi @Wagnerp,
> 
> Do you have time for this one?

Hi @giduac 

Possibly not, expecting a few busy weeks ahead grappling with my new projects

**Comment by giduac** [comment] 2024-07-17 07:30
@Wagnerp 
Then assign to me please.

**Comment by Wagnerp** [comment] 2024-07-17 07:33
> @Wagnerp Then assign to me please.

@giduac 

Done

**Comment by giduac** [comment] 2024-07-18 05:12
Hi @Wagnerp,
cc.: @Smurf-IV 

I've had a look at `ToolBarImageStorage.cs`.

Would it be an idea to have all image properties independently react to changes that need saving in the designer file instead of the current approach of saving all to the designer file is one has changed.
```cs
        /// <summary>Gets the toolbar images.</summary>
        [Category(@"Visuals")]
        [Description(@"A collection of images that are used in toolbars.")]
        [MergableProperty(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [Localizable(true)]
        public ToolBarImageStorage ToolbarImages => ToolbarImageStorage;

        private bool ShouldSerializeToolbarImages() => !ToolbarImageStorage.IsDefault;
        private void ResetToolbarImages() => ToolbarImageStorage.Reset();
```
That would mean that `private bool ShouldSerializeToolbarImages() => !ToolbarImageStorage.IsDefault;` can be removed?

To compare images it would need a pixel to pixel comparison which can be CPU intensive and imo overkill in this situation. Using a bool to signal that an image has changed through the image property setter is sufficient in this case.

**Comment by Smurf-IV** [comment] 2024-07-18 07:03
I think that is overkill.
How about an struct { image, bool }
That is serialised, and the bool is set to state that the image has been set in the designer (Or programatically).
And only serialise if the struct exists (or bool is not false) for each image.
Then there is no need for actual pixel (or sizing) check requirements. 

??

**Comment by giduac** [comment] 2024-07-18 07:29
@Smurf-IV, @Wagnerp 

Bool was my first idea also. 

But the first if in the code block above would also be quick routine and bit more precise than a bool indicator.
```cs
            // First filter on base properties.
            // Only if those are equal a pixel comparison needs to be done.
            if ( !image.Size.Equals( imageToCompare.Size )
                || !image.PhysicalDimension.Equals( imageToCompare )
                || image.PixelFormat != imageToCompare.PixelFormat
                || image.VerticalResolution != imageToCompare.VerticalResolution
                || image.HorizontalResolution != imageToCompare.HorizontalResolution
                )
            {
                return false;
            }
```

....???

**Comment by giduac** [comment] 2024-07-18 11:41
@Smurf-IV, @a & @Wagnerp,

This shows the main alterations for the `ToolBarImageStorage` class.
Following @Smurf-IV 's advice it can be done like this. 
```cs
    [TypeConverter(typeof(ExpandableObjectConverter))]
    public class ToolBarImageStorage : Storage
    {
        #region ImageResource
        /// <summary>
        /// Image Resource record that holds the intial image set on instantiation.<br/>
        /// When the Image property receives another assignment ShouldSerialize will be set to true.
        /// </summary>
        private struct ImageResource
        {
            private Image _initialImage;
            private Image _image;

            /// <summary>
            /// Default custom constructor
            /// </summary>
            /// <param name="image">The image to intialize the record with.</param>
            public ImageResource(Image image)
            {
                _image = image;
                _initialImage = image;
                ShouldSerialize = false;
            }

            /// <summary>
            /// Image property
            /// </summary>
            public Image Image 
            {
                get => _image;

                set
                {
                    _image = value;
                    ShouldSerialize = true;
                }
            }

            /// <summary>
            /// If the image should be serialized by the designer
            /// </summary>
            public bool ShouldSerialize 
            {
                get;
                set;
            }

            /// <summary>
            /// Resets the record to it's initial state
            /// </summary>
            public void Reset()
            {
                Image = _initialImage;
                ShouldSerialize = false;
            }
        }
        #endregion

        #region Instance Fields
        private ImageResource _new = new(GenericToolbarImageResources.GenericNewDocument);
        private ImageResource _open = new(GenericToolbarImageResources.GenericOpenFolder);
        private ImageResource _save = new(GenericToolbarImageResources.GenericSave);
        private ImageResource _saveAs = new(GenericToolbarImageResources.GenericSaveAs);
        private ImageResource _saveAll = new(GenericToolbarImageResources.GenericSaveAll);
        private ImageResource _cut = new(GenericToolbarImageResources.GenericCut);
        private ImageResource _copy = new(GenericToolbarImageResources.GenericCopy);
        private ImageResource _paste = new(GenericToolbarImageResources.GenericPaste);
        private ImageResource _undo = new(GenericToolbarImageResources.GenericUndo);
        private ImageResource _redo = new(GenericToolbarImageResources.GenericRedo);
        private ImageResource _pageSetup = new(GenericToolbarImageResources.GenericPrintSetup);
        private ImageResource _printPreview = new(GenericToolbarImageResources.GenericPrintPreview);
        private ImageResource _print = new(GenericToolbarImageResources.GenericPrint);
        private ImageResource _quickPrint = new(GenericToolbarImageResources.GenericQuickPrint);

        private List<Image> _toolBarImages;
        #endregion

        #region Identity

        /// <summary>Initializes a new instance of the <see cref="ToolBarImageStorage" /> class.</summary>
        public ToolBarImageStorage()
        {
            _toolBarImages = new List<Image>();
        }

        #endregion

        #region Public

        public Image Open 
        {
            get => _open.Image;
            set => _open.Image = value;
        }

        public void ResetOpen() => _open.Reset();
        public bool ShouldSerializeOpen() => _open.ShouldSerialize;

```

???

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-18 11:57
@Smurf-IV & @giduac 

I'm not sure I understand why image comparison (or even detecting change) is required here. Isn't reference equality (current logic) sufficient for this purpose?

I didn't dig deeper or try to test this, but looking at the code, the constructor of `ToolBarImageStorage` calls `Reset();`, which assigns a reference of the images (from the static fields) to the corresponding properties, so by default, `.Equals()` should return true unless the image is changed. Please correct me if I'm missing something.

**Comment by Ahmed-Abdelhameed** [comment] 2024-07-18 12:06
Okay, I just tested this with an instance of `KryptonManager` and `kryptonManager1.ToolkitImages.ToolbarImages.IsDefault` does indeed return true.

**Comment by giduac** [comment] 2024-07-18 13:03
> @Smurf-IV & @giduac
> 
> I'm not sure I understand why image comparison (or even detecting change) is required here. Isn't reference equality (current logic) sufficient for this purpose?
> 
> I didn't dig deeper or try to test this yet, but looking at the code, the constructor of `ToolBarImageStorage` calls `Reset();`, which assigns a reference of the images (from the static fields) to the corresponding properties, so by default, `.Equals()` should return true unless the image is changed. Please correct me if I'm missing something.

@Ahmed-Abdelhameed,

So from your point of view this should be sufficient:

```cs
            public bool ShouldSerialize 
            {
                get => _initialImage.Equals(_image);
            }
``

**Comment by giduac** [comment] 2024-07-18 13:20
@Ahmed-Abdelhameed 

Which brings me to this Struct.

```cs
        private struct ImageResource
        {
            private Image _initialImage;

            /// <summary>
            /// Default custom constructor
            /// </summary>
            /// <param name="image">The image to intialize the record with.</param>
            public ImageResource(Image image) => Image = _initialImage = image;

            /// <summary>
            /// Image property
            /// </summary>
            public Image Image { get; set; }

            /// <summary>
            /// If the image should be serialized by the designer
            /// </summary>
            public bool ShouldSerialize => _initialImage.Equals(Image);

            /// <summary>
            /// Resets the record to it's initial state
            /// </summary>
            public void Reset() => Image = _initialImage;
        }
```

**Comment by giduac** [comment] 2024-07-18 13:53
@Ahmed-Abdelhameed 
Well we wont be copying structs around here so in this case I don't see big problems arising.
On the other hand if these are used a lot it would be less work for the GC.

**Comment by Wagnerp** [comment] 2024-07-18 15:58
Hi @giduac, @Smurf-IV & @Ahmed-Abdelhameed 

Just unwinding the conversation a little. I do also think that comparing images pixel wise would be overkill and is unnecessarily taxing the CPU. The `Storage` class does expect a bool `IsDefault` return value, which in this case is the problem. Using a struct is fine in this instance, if it's just holding default values.

**Comment by giduac** [comment] 2024-07-18 16:02
@Wagnerp,

Which is the purpose of `ReturnToolBarImages()` routine and connected code?

**Comment by Wagnerp** [comment] 2024-07-18 16:13
> @Wagnerp,
> 
> Which is the purpose of `ReturnToolBarImages()` routine and connected code?

@giduac 

Where's that?

**Comment by giduac** [comment] 2024-07-18 16:25
> > @Wagnerp,
> > Which is the purpose of `ReturnToolBarImages()` routine and connected code?
> 
> @giduac
> 
> Where's that?

https://github.com/Krypton-Suite/Standard-Toolkit/blob/alpha/Source/Krypton%20Components/Krypton.Toolkit/Storage/Images/Toolbar/ToolBarImageStorage.cs#L140

**Comment by Wagnerp** [comment] 2024-07-18 16:47
> > > @Wagnerp,
> > > Which is the purpose of `ReturnToolBarImages()` routine and connected code?
> > 
> > 
> > @giduac
> > Where's that?
> 
> https://github.com/Krypton-Suite/Standard-Toolkit/blob/alpha/Source/Krypton%20Components/Krypton.Toolkit/Storage/Images/Toolbar/ToolBarImageStorage.cs#L140

@giduac 

I remember now... it was supposed to get the images for the themes. VS should tell you where it's being used if you press `Ctrl + Left Click` on it.

**Comment by Wagnerp** [comment] 2024-07-18 17:35
> @Wagnerp, @Ahmed-Abdelhameed & @Smurf-IV
> 
> Serializing this makes no sense. Because every time you switch themes in the designer or at runtime the custom image get lost. Also when switching themes all the images get replaced by the selected theme's images and differ from the base/initial image. Which causes all the images being written to the designer source.
> 
> So if the dev want to assign a custom image that has to be done after theme switch.
> 
> Your thought please on this one....
> 
> Source: https://github.com/Krypton-Suite/Standard-Toolkit/blob/alpha/Source/Krypton%20Components/Krypton.Toolkit/Storage/Images/Toolbar/ToolBarImageStorage.cs

I'd say remove it :)

**Comment by giduac** [comment] 2024-07-18 18:11
> @Wagnerp, @Ahmed-Abdelhameed & @Smurf-IV

@Wagnerp, @Ahmed-Abdelhameed & @Smurf-IV

What is the exact purpose of this class / what has it to accomplish?

**Comment by Wagnerp** [comment] 2024-07-18 18:15
> > @Wagnerp, @Ahmed-Abdelhameed & @Smurf-IV
> 
> @Wagnerp, @Ahmed-Abdelhameed & @Smurf-IV
> 
> What is the exact purpose of this class / what has it to accomplish?

@giduac 

It was designed to allow the developer/user to set custom images for these entries (if they wanted to) via the `KryptonManager`.

**Comment by giduac** [comment] 2024-07-18 18:25
@Wagnerp 
And these are for the Ribbon QAT ?

**Comment by Wagnerp** [comment] 2024-07-18 18:26
> @Wagnerp And these are for the Ribbon QAT ?

Yes

**Comment by giduac** [comment] 2024-07-18 19:06
@Wagnerp 
How is this integrated in the ribbon?

**Comment by giduac** [comment] 2024-07-19 14:21
@Wagnerp

How is this integrated in the ribbon?

**Comment by Wagnerp** [comment] 2024-07-19 14:23
> @Wagnerp
> 
> How is this integrated in the ribbon?

@giduac 

I don't think it is/was

**Comment by giduac** [comment] 2024-07-19 14:37
@Smurf-IV, @Wagnerp & @Ahmed-Abdelhameed 

[Since the latest findings](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1632#issuecomment-2237137139) a chat about what this class should accomplish is needed before we can proceed.

**Comment by Smurf-IV** [comment] 2024-07-20 07:49
> > @Wagnerp
> > How is this integrated in the ribbon?
> 
> @giduac
> 
> I don't think it is/was

So it should be removed, so that it does not impact V90 work.
And current users of designers will not get polluted serialisation for things that are supposed default !

**Comment by giduac** [comment] 2024-07-26 07:01
Handled in #1657

**Closed by giduac** 2024-07-26 07:01 UTC
Labels: bug, under investigation, area:designer, area:toolkit, version:90
