### ISSUE TITLE
[Bug]: Components are drawn differently between designer and executed app

### ISSUE THREAD

**Issue by da-kil** [Krypton-Suite/Standard-Toolkit#1517] opened 2024-06-11 20:27 UTC
**Describe the bug**
Components are drawn differently between designer and executed app. See screenshots.

**To Reproduce**
-

**Expected behavior**
There must be no difference

**Screenshots**
Designer:
![ButtonsCorrect](https://github.com/Krypton-Suite/Standard-Toolkit/assets/112584984/76ae6cb8-c356-4c47-99d2-df2a7364535c)

Running App (elements are disabled on purpose):
![Buttons](https://github.com/Krypton-Suite/Standard-Toolkit/assets/112584984/fc92a276-3076-4f51-bfa7-264d08fb7deb)

Designer:
![ButtonCorrect](https://github.com/Krypton-Suite/Standard-Toolkit/assets/112584984/ddc1d3d6-315a-43b0-9ed1-0fa7dc3d750f)

Running App (elements are disabled on purpose):
![Button](https://github.com/Krypton-Suite/Standard-Toolkit/assets/112584984/c17faad3-1644-486e-98a0-86e534f0397a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 80.24.3.64
 - Framework/.NET Version: net8.0-windows
 - Toolkit Version: 80.24.3.64

**Additional context**
-

**Comment by giduac** [comment] 2024-06-12 06:12
Hi @da-kil,

Can you post a small sample program that exposes the problem.
Thank  you.

**Comment by MattH-Work** [comment] 2024-06-12 11:20
Had a similar issue recently, setting the forms AutoScaleMode from Font to DPI solved the problem

**Comment by giduac** [comment] 2024-06-12 18:38
Hi @da-kil,

I tried @MattH-Work 's advise but can't reproduce this.

A sample program that reproduces the problem is much appreciated?

**Comment by giduac** [comment] 2024-06-12 18:39
@Wagnerp,
Please assign to me.
Thanks.

**Comment by Wagnerp** [comment] 2024-06-13 06:30
@giduac Done, I've added it to the v85 milestone

**Comment by giduac** [comment] 2024-06-13 19:16
@da-kil 

If a new ktextbox is added to the same form how does tat behave?

**Comment by da-kil** [comment] 2024-06-13 20:20
> @da-kil
> 
> If a new ktextbox is added to the same form how does tat behave?

only if I add the whole group. For a single ktextbox it works as expected

**Comment by giduac** [comment] 2024-06-13 21:30
What "group" is that exactly?

**Comment by Smurf-IV** [comment] 2024-06-14 06:36
> it is a rather old application originally written with .NET 2.0.

I would have a look at the anchors for each of the controls.
Ans also set the scaling to none to see if that partly solves the issue (See anchors)
What have you got in your manifest file to deal with the scaling done by windows itself ?
If everything else fails, then use a flowtable with a single row, and set the cells to autosize (This will also force the anchoring issue to go away ;-)

**Comment by giduac** [comment] 2024-06-16 09:52
@Wagnerp or @Smurf-IV 
Please add the "waiting for feedback" label.

**Comment by Smurf-IV** [comment] 2024-06-16 12:55
> @Wagnerp or @Smurf-IV Please add the "waiting for feedback" label.

It was already there. Set 4 days ago, or Did I miss something else ?

**Comment by giduac** [comment] 2024-06-19 07:07
Hi @da-kil,

What is the status of this?

**Comment by giduac** [comment] 2024-06-25 05:55
Hi @Wagnerp,

Please close as the @da-kil does not responds queries.
If needed the ticket can be reopened.

**Comment by da-kil** [comment] 2024-06-25 06:21
Hi,
sorry, totally forgot. Yes, close it, as I think it is more application related and some tips from @Smurf-IV are helpful

**Comment by giduac** [comment] 2024-06-25 06:37
@da-kil TY! :)

**Closed** 2024-06-25 06:59 UTC
Labels: bug, under investigation, awaiting feedback, area:designer, area:toolkit, version:85
