### ISSUE TITLE
[New Feature Request]: Progressbar

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#5] opened 2020-04-01 17:27 UTC
[#234](https://github.com/Krypton-Suite-Legacy/Krypton-NET-5.470/issues/234)

**Comment by Wagnerp** [comment] 2020-10-13 14:59
here is a starting point:
https://stackoverflow.com/questions/20584132/change-the-color-of-a-toolstripprogressbar-without-disabling-the-xp-visual-style

Using the above, I have got a "Reasonable colour background" with the following event added to the status strip:

        private void StatusStrip_RendererChanged(object sender, EventArgs e)
        {
            if ( ToolStripManager.Renderer is KryptonProfessionalRenderer kpr )
                progressBar.BackColor= kpr.KCT.StatusStripGradientEnd;
        }

I wonder if this would help https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/walkthrough-creating-a-professionally-styled-toolstrip-control

**Comment by Smurf-IV** [comment] 2021-08-08 06:42
Closing as duplicate of #203

**Closed by Smurf-IV** 2021-08-08 06:42 UTC
Labels: enhancement, help wanted, new feature, suggestion

**Comment by Smurf-IV** [comment] 2021-10-17 09:04
@Wagnerp How do I get the data associated with link 234 in the Opening comment ?

**Comment by Wagnerp** [comment] 2021-10-17 11:27
> @Wagnerp How do I get the data associated with link 234 in the Opening comment ?

@Smurf-IV Do you mean #234?

**Comment by Wagnerp** [comment] 2021-10-18 07:22
> No.. From the Archived , See the link details at the top

@Smurf-IV It should now work :)
