### ISSUE TITLE
[Bug]: Krypton Navigator Exception

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#1035] opened 2023-06-27 18:15 UTC
Krypton navigator tabs not showing up in designer, and when running application I get the following exception. This was not present in Canary 80.23.2.51 and appeared in Canary 80.23.4.114.

Object reference not set to an instance of an object.
at Krypton.Navigator.KryptonPage.OnTabStopChanged(EventArgs e)
at System.Windows.Forms.Control.set_TabStop(Boolean value)
at System.Windows.Forms.Panel..ctor()
at Krypton.Toolkit.VisualPanel..ctor()
at Krypton.Navigator.KryptonPage..ctor(String text, Bitmap imageSmall, String uniqueName, Size minSize)
at Krypton.Navigator.KryptonPage..ctor(String text, Bitmap imageSmall, String uniqueName)
at Krypton.Navigator.KryptonPage..ctor(String text, String uniqueName)
at Krypton.Navigator.KryptonPage..ctor()
at MotionView.AppUI.InitializeComponent() in C:\Users\sethd\Documents\TFS\MotionView\MotionView\MotionView\App\AppMainUI\AppUI.Designer.cs:line 169

Note that as of Canary 80.23.6.117 this issue is still present, but the exception is different:

Object reference not set to an instance of an object.
at Krypton.Navigator.KryptonPage.OnAppearancePropertyChanged(String propertyName)
at Krypton.Navigator.KryptonPage.set_Text(String value)
at Krypton.Navigator.KryptonPage..ctor(String text, Bitmap imageSmall, String uniqueName, Size minSize)
at Krypton.Navigator.KryptonPage..ctor(String text, Bitmap imageSmall, String uniqueName)
at Krypton.Navigator.KryptonPage..ctor(String text, String uniqueName)
at Krypton.Navigator.KryptonPage..ctor()
at MotionView.AppUI.InitializeComponent() in C:\Users\sethd\Documents\TFS\MotionView\MotionView\MotionView\App\AppMainUI\AppUI.Designer.cs:line 169

**Comment by Wagnerp** [comment] 2023-06-27 18:28
Duplicate of #1020

**Comment by Wagnerp** [comment] 2023-06-27 18:32
@sdreb3421 This should be fixed in the July canary build

**Comment by sdreb3421** [comment] 2023-06-27 18:41
@Wagnerp awesome. Looks like it's likely a duplicate, but our issue is existing navigator tabs not showing up, versus the previous issue is not being able to add tabs. Thanks!

**Comment by Wagnerp** [comment] 2023-06-28 16:14
@sdreb3421 Could you please verify if this bug is still present in the latest nightly build?

**Comment by sdreb3421** [comment] 2023-06-28 21:15
@Wagnerp Fixed on nightly 80.23.6.168. Well done.

**Comment by Wagnerp** [comment] 2023-07-01 16:41
@sdreb3421 Can this be closed?

**Comment by sdreb3421** [comment] 2023-07-01 16:50
Yeah, nice work!

**Closed** 2023-07-01 16:51 UTC
Labels: bug, duplicate, fixed
