### ISSUE TITLE
[Feature Request]: Ability to host a `KryptonRibbon` in a `UserControl`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Standard-Toolkit#1354] opened 2024-02-25 10:16 UTC
Originally from @Tape-Worm

The ability to host the ribbon on a `UserControl`.

My current setup uses plug in architecture to load modules into the application. These plug ins can have their own ribbon tabs on my main ribbon. So, naturally, if the plug in isn't loaded, then the tab shouldn't be there. And because of the dynamic nature of this system, I can't reasonably add all the tabs that may be needed (e.g. end users may want their own plug ins, and I very well can't predict their needs).

To get around this limitation, I've had to create a dummy form in my plug in, and expose the ribbon back via that so I can merge the tabs (in my custom merging code, see item number 2) from the dummy into the main ribbon on plug in load. As you can imagine, this is very cumbersome.

If I could host the ribbon on the same user control that gets loaded in by the plug in, it would save me a lot of grief, not to mention a lot of boilerplate code to facilitate communication between the user control and the dummy form.

I know this can be done, as we use the Developer Express ribbon at work, and it can do this easily.

**Comment by Smurf-IV** [comment] 2024-02-25 11:30
Duplicate of #594

**Closed by Smurf-IV** 2024-02-25 11:30 UTC
Labels: enhancement, new feature, suggestion, area:ribbon
