### ISSUE TITLE
[Bug]: "System.Drawing.dll" Argument exception thrown with KryptonTableLayoutPanel when scaling set to 150%

### ISSUE THREAD

**Issue by NintendoPlayer** [Krypton-Suite/Standard-Toolkit#754] opened 2022-06-17 09:15 UTC
Hi!
There is a component in my software that cracks when Windows is scaled to other than 100%.  Right now we are changing screens from 1080p to 4k and people are scaling  and there are problems.  I have 

The exception is in a particular method of control KryptonTableLayoutPanel:
```c#
private void BackGroundPanel_Refreshed()
        {
            _bm = new Bitmap(_backGroundPanel.Width, _backGroundPanel.Height, PixelFormat.Format32bppRgb);
            _backGroundPanel.DrawToBitmap(_bm,
                new Rectangle(0, 0, _backGroundPanel.Width, _backGroundPanel.Height));
            BackgroundImage = _bm;
        }
```
This is part of the stacktrace of the exception thrown:

```
Fallo en NewPanelSeleccion: El parámetro no es válido.

   en System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   
   en Krypton.Toolkit.KryptonTableLayoutPanel.BackGroundPanel_Refreshed()
   
   en Krypton.Toolkit.KryptonTableLayoutPanel.SetToBehindTable()
   
   en Krypton.Toolkit.KryptonTableLayoutPanel.OnSizeChanged(EventArgs e)
```
Itt goes on, but this is the important part.  If I change the KryptonTableLayoutPanel for a Forms.TableLayoutPanel everything works fine.

I'm working with Nightlies 65.22.3.77-alpha.  I don't know if this is solved on newer versions because nightlies are on 70.XX and I'm stil on VS 2019.  Probably will change to stable channel but right now I don't want to change if it's not needed.

Thank you!

P.D: Please correct my code, I'm still figuring out how the code brackets work
Edit: Done

**Comment by Smurf-IV** [comment] 2022-06-17 17:37
I am unable to reproduce with the demo app using last week alpha code running .net48:
![image](https://user-images.githubusercontent.com/2418812/174349713-372d88c8-c838-4db6-8afa-9b9d850dea9d.png)

Can you provide a simplified example please ?

**Comment by Smurf-IV** [comment] 2022-06-17 17:37
Note .net6.0 is also okay.

**Comment by Wagnerp** [comment] 2022-07-07 15:13
> @Wagnerp has this been fixed now ?

@Smurf-IV Is this working in .NET 7? If so, it can be marked as fixed.

**Comment by Smurf-IV** [comment] 2022-07-08 06:38
> > @Wagnerp has this been fixed now ?
> 
> @Smurf-IV Is this working in .NET 7? If so, it can be marked as fixed.

No Idea, Still developing / testing in .net48 at the moment.

**Comment by Smurf-IV** [comment] 2022-07-16 09:34
@NintendoPlayer 

> Can you provide a simplified example please ?

**Comment by NintendoPlayer** [comment] 2022-08-02 13:51
@Smurf-IV Hi!  Sorry for the delay.  I can't upgrade Visual Studio 2019 at the moment so I can upgrade to the last version of Krypton to test if I still have the issue.  But it was really simple, just having the KryptonTableLayoutPanel on the constructor of the usercontrol with a 150% scaling prompted the error.   Changing the to a winform tablelayoutpanel or changing the scale to 100% solved the issue.

**Comment by Smurf-IV** [comment] 2022-08-03 05:58
> I can't upgrade Visual Studio 2019 at the moment so I can upgrade to the last version of Krypton to test 

Not sure I understand.. Krypton will work wherever .Net4.6.2 can be compiled onwards...
If you are not using the latest, then you may be just banging up against an old bug !

**Comment by NintendoPlayer** [comment] 2022-08-03 08:16
@Smurf-IV Sorry, thought that version 7X was not compatible with <NET 5.  I update to the last nightly and the issue is gone.

**Closed** 2022-08-04 06:13 UTC
Labels: bug, awaiting feedback

**Comment by Wagnerp** [comment] 2022-08-04 06:27
> @Smurf-IV Sorry, thought that version 7X was not compatible with <NET 5. I update to the last nightly and the issue is gone.

Hi @NintendoPlayer 

Support was ended for just .NET 5 in v70 'lite' packages, but not the full packages, as it reached EOL back in May
