### ISSUE TITLE
[Bug]: ButtonSpec does not open assigned context menu when clicked

### ISSUE THREAD

**Issue by cuppm** [Krypton-Suite/Standard-Toolkit#1508] opened 2024-06-03 13:46 UTC
**Describe the bug**
A `ButtonSpec` with a `Type` set to `Context` used to automatically open the assigned `KryptonContextMenu` when clicked in version 70.22.11.312.  In the current version it does nothing when clicked and I have to add a click handler to manually open the context menu.

**To Reproduce**
1. Add a `ButtonSpec` to something
2. Set `Type = Context` (not sure if this was required before, I just used that for the icon)
3. Assign a `KryptonContextMenu`
4. Run app and click the `ButtonSpec`

**Expected behavior**
The assigned context menu should open when the button is clicked.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2 (19045.4412)
 - Framework/.NET Version: 4.8 
 - Toolkit Version: 80.24.03.64

**Comment by giduac** [comment] 2024-06-17 20:56
Hi @Wagnerp,
Please assign to me.
TY.

**Comment by giduac** [comment] 2024-06-17 21:04
Hi @cuppm,

Been looking into your ticket.

The V70 & upcoming V90 release work fully.

The V80 release (you're using) has a perk to it.
- The ButtonSpec has a new property named `ShowDrop`.
- This enables a DropDown arrow next to the button.
- Only the area of the DropDown arrow will show the menu (see video).

https://github.com/Krypton-Suite/Standard-Toolkit/assets/96108132/e282ab45-c66c-4422-bd52-1ca7bad617f0

**Comment by giduac** [comment] 2024-06-17 21:14
Hi @Wagnerp & @Smurf-IV,

Please, first, see the findings above.

Seems that the `ShowDrop` functionality (new in V80) has been extended to the full button in V90. As where the V80 only shows the menu when the dropdown arrow is clicked.

If this was the initial intended behaviour for V80 then that would not be a bug of course...
Shall we leave this in V80 as it is or add the the V90 functionality ?

**Comment by cuppm** [comment] 2024-06-17 21:55
If this was an intended thing, I would think a breaking change note would be helpful to include since we wouldn't otherwise know to make that property change if it was originally designed in an older version of Krypton.

Also the current property description for it in the designer with v80 doesn't seem accurate: 
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/1964795/3a80e423-d172-481d-838e-8be82170850b)

**Comment by giduac** [comment] 2024-06-17 22:19
> If this was an intended thing, I would think a breaking change note would be helpful to include since we wouldn't otherwise know to make that property change if it was originally designed in an older version of Krypton.
> 
> Also the current property description for it in the designer with v80 doesn't seem accurate: ![image](https://private-user-images.githubusercontent.com/1964795/340464819-3a80e423-d172-481d-838e-8be82170850b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NjI5MzUsIm5iZiI6MTcxODY2MjYzNSwicGF0aCI6Ii8xOTY0Nzk1LzM0MDQ2NDgxOS0zYTgwZTQyMy1kMTcyLTQ4MWQtODM4ZS04YmU4MjE3MDg1MGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMjIxNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWFlMzUxYmNmNjQyNDcxNDBmOTVjMzFkMDA4MTk4NjYyOGM5NDg4Y2JjZGUzNWYyZDA3ZmFmOGM2YzZmZDQwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PhG5LU_7zf6atdGv_QgKD_-zWvL7d_67aBoM_oIs73o)
@cuppm 

Indeed needs some tlc.. :)

**Comment by Wagnerp** [comment] 2024-06-18 06:43
Hi @cuppm & @giduac 

This links back to https://github.com/Krypton-Suite/Standard-Toolkit/issues/962

**Comment by giduac** [comment] 2024-06-18 06:52
@Wagnerp & @Smurf-IV,

Well, the question is/was do we leave the V80 functionality as it is (see comments to cuppm) or does it need updating to the V90 version ?

**Comment by Wagnerp** [comment] 2024-06-18 06:55
> @Wagnerp & @Smurf-IV,
> 
> Well, the question is/was do we leave the V80 functionality as it is (see comments to cuppm) or does it need updating to the V90 version ?

Hi @giduac 

I'd say update it to the V90 version & add it to the `Breaking Changes` block in `README.md`.

**Comment by giduac** [comment] 2024-06-18 14:28
Hi @cuppm,

Thanks for pointing this out to us.

TLC  :-) applied, to the V80 release branch, it will be part of the upcoming V80 release. And for the new V90 the description has been updated. So the behaviour will now be the same for V80 & V90.

**Changelog entry details for V80**
- Added property `ShowDrop`, which displays a drop down arrow on the button.
- When a `KryptonContextMenu` is connected the menu is shown when the button is clicked.
- When a WinForms `ContextMenuStrip` is connected the menu is shown when the button is clicked.
- When both type of the above ContextMenus are connected the `KryptonContextMenu` takes precedence.
- The ButtonSpec's `Type` property does not need setting to "Context" to display the menu.

PR's are underway.

**Comment by giduac** [comment] 2024-06-19 06:37
Hi@Wagnerp,

The fix is in, please close the ticket.
TY.

**Closed** 2024-06-19 06:41 UTC
Labels: bug, fixed, regression, area:toolkit
