### ISSUE TITLE
[Bug]: KryptonForm RTL issue

### ISSUE THREAD

**Issue by NetworkStream** [Krypton-Suite/Standard-Toolkit#786] opened 2022-07-19 05:47 UTC
hello , i have problem with KryptonForm with  RTL enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/59274488/179674474-883dcb9d-bc73-4cd0-9ef6-cb331b8f17fa.png)

thanks in advance.

**Comment by Wagnerp** [comment] 2022-07-19 08:09
Duplicate of #343

**Comment by Wagnerp** [comment] 2022-07-28 07:56
@Smurf-IV Given that the close, maximise etc are all individual buttonspecs, could they theoretically be moved depending on the RTL setting?

@NetworkStream Can you give us a screenshot of a normal WinForm form in the RTL layout please?

**Comment by Smurf-IV** [comment] 2022-07-31 15:01
> @Smurf-IV Given that the close, maximise etc are all individual buttonspecs, could they theoretically be moved depending on the RTL setting?

Yes, of course they should be (Including the help)

Please close this and use the linked item (https://github.com/Krypton-Suite/Standard-Toolkit/issues/343#issuecomment-968865656) as it has better pictures and explanations

**Closed** 2022-07-31 15:14 UTC
Labels: bug, duplicate
