### ISSUE TITLE
[Bug]: Not Implemented Exception thrown for `GetRibbonBackColorStyle` `PaletteOffice2010Base.cs`

### ISSUE THREAD

**Issue by DigitalMills** [Krypton-Suite/Standard-Toolkit#1715] opened 2024-08-06 16:23 UTC
**Describe the bug**
Not Implemented Exception thrown for GetRibbonBackColorStyle for PaletteOffice2010Base.cs

**To Reproduce**
1. Attempt to render and paint a Ribbon Group component

**Expected behavior**
Ribbon Group renders and paints

**Actual behavior**
Error is thrown, suggesting part of the flow is not yet implemented. Stack trace:

System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://github.com/Krypton-Suite/Standard-Toolkit/issues/new/choose' with working directory 'C:\Git\Aireforge\Aireforge Suite\OmniCompare\bin\Debug\net8.0-windows'. The system cannot find the file specified.
  at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
  at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
  at Krypton.Toolkit.DebugTools.NotImplemented(String outOfRange, String callingFilePath, Int32 lineNumber, String callingMethod)
  at Krypton.Toolkit.PaletteOffice2010Base.GetRibbonBackColorStyle(PaletteRibbonBackStyle style, PaletteState state)
  at Krypton.Toolkit.PaletteRedirect.GetRibbonBackColorStyle(PaletteRibbonBackStyle style, PaletteState state)
  at Krypton.Toolkit.PaletteRibbonBackInheritRedirect.GetRibbonBackColorStyle(PaletteState state)
  at Krypton.Toolkit.PaletteRibbonBack.GetRibbonBackColorStyle(PaletteState state)
  at Krypton.Toolkit.PaletteRibbonBack.GetRibbonBackColorStyle(PaletteState state)
  at Krypton.Ribbon.ViewDrawRibbonGroup.RenderNormalBefore(RenderContext context)
  at Krypton.Ribbon.ViewDrawRibbonGroup.RenderBefore(RenderContext context)
  at Krypton.Toolkit.ViewComposite.Render(RenderContext context)
  at Krypton.Toolkit.ViewComposite.Render(RenderContext context)
  at Krypton.Toolkit.ViewControl.OnPaint(PaintEventArgs e)
  at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
  at System.Windows.Forms.Control.WmPaint(Message& m)
  at System.Windows.Forms.Control.WndProc(Message& m)
  at Krypton.Toolkit.ViewControl.WndProc(Message& m)
  at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
  at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Screenshots**
![image](https://github.com/user-attachments/assets/66f38dbc-ec5c-457e-8dd4-0171a5f17722)

**Desktop (please complete the following information):**

OS: Microsoft Windows 11 Business
Version: 10.0.22631 Build 22631
Framework/.NET Version: net8.0-windows
Toolkit Version: 90.24.7.204-beta

**Comment by Wagnerp** [comment] 2024-08-16 06:26
Hi @DigitalMills 

Does this happen when an event has occurred, I.e. hovering over it?

**Comment by DigitalMills** [comment] 2024-08-22 15:41
Hi @Wagnerp, this occurs when attempting to render any form.cs with a ribbon group component within it. The issue occurs before any hover events can take place.

**Comment by Wagnerp** [comment] 2024-08-22 15:55
> Hi @Wagnerp, this occurs when attempting to render any form.cs with a ribbon group component within it. The issue occurs before any hover events can take place.

Hi @DigitalMills 

Can you try `nightly` please, as I think it's been fixed?

**Comment by DigitalMills** [comment] 2024-08-28 14:47
Hi @Wagnerp ,

Unfortunately we're still experiencing the same issue on the latest `nightly` build.

thanks

**Comment by Wagnerp** [comment] 2024-08-28 14:50
Hi @DigitalMills 

Is it possible to upload a clip to show what's going on?

**Comment by DigitalMills** [comment] 2024-08-28 15:42
Hi @Wagnerp,

please find video and screenshot attached:

https://github.com/user-attachments/assets/292e3b75-5af7-4868-a1b9-d4570afdb802

![image](https://github.com/user-attachments/assets/9519f701-3590-4ac0-a84f-9a15bd664a59)

**Comment by Wagnerp** [comment] 2024-08-28 17:12
Hi @DigitalMills 

Does it just happen on a contextual tab?

**Comment by DigitalMills** [comment] 2024-08-29 15:16
Here's our stack trace for you, appears to relate to Krypton.Toolkit.PaletteOffice2010Base.GetRibbonBackColorStyle.

It seems closely associated with the Ribbon Group component

   at System.Windows.Forms.MessageBox.Show(String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton)
   at Krypton.Toolkit.DebugTools.NotImplemented(String outOfRange, String callingFilePath, Int32 lineNumber, String callingMethod)
   at Krypton.Toolkit.PaletteOffice2010Base.GetRibbonBackColorStyle(PaletteRibbonBackStyle style, PaletteState state)
   at Krypton.Toolkit.PaletteRedirect.GetRibbonBackColorStyle(PaletteRibbonBackStyle style, PaletteState state)
   at Krypton.Toolkit.PaletteRibbonBackInheritRedirect.GetRibbonBackColorStyle(PaletteState state)
   at Krypton.Toolkit.PaletteRibbonBack.GetRibbonBackColorStyle(PaletteState state)
   at Krypton.Toolkit.PaletteRibbonBack.GetRibbonBackColorStyle(PaletteState state)
   at Krypton.Ribbon.ViewDrawRibbonGroup.RenderNormalBefore(RenderContext context)
   at Krypton.Ribbon.ViewDrawRibbonGroup.RenderBefore(RenderContext context)
   at Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   at Krypton.Toolkit.ViewComposite.Render(RenderContext context)
   at Krypton.Toolkit.ViewControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Krypton.Toolkit.ViewControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by Wagnerp** [comment] 2024-08-29 17:25
Hi @DigitalMills 

Is this a duplicate of #1299?

cc. @Smurf-IV & @giduac

**Comment by giduac** [comment] 2024-08-30 13:59
Hi @DigitalMills (cc: @Wagnerp )

We need a bit more info to be able replicate this properly:
- What is happening in code to the ribbon when the button is clicked and the contextual tab is opened?
- Which theme does this occur with?

![image](https://github.com/user-attachments/assets/13ae4b32-62e0-4bb6-b6dc-de31d56dd959)

**Comment by giduac** [comment] 2024-08-30 14:01
> Hi @DigitalMills
> 
> Is this a duplicate of #1299?
> 
> cc. @Smurf-IV & @giduac

@Wagnerp 
Indeed it seems that this present in more themes. :thumbsup:

**Comment by Wagnerp** [comment] 2024-08-30 18:15
Hi @DigitalMills 

Is it possible to attach a sample?

@giduac 

Is it possible to get the values into a buffer.

**Comment by DigitalMills** [comment] 2024-09-02 15:22
@PWagner1  for my error the state being sent that throws an error is 'ContextNormal'

![image](https://github.com/user-attachments/assets/e1802cbd-07c5-4f2c-8749-c0173ea50da8)

Seems one of the PaletteRibbonBackStyle types is missing a PaletteState of ContextNormal:

**Comment by giduac** [comment] 2024-09-02 16:23
@DigitalMills 

Thanks for the response. Indeed we found this as well.

We both might reproduce the error in a different way.
Therefore, what we would like to know from you is how the error is provoked in code on your side. So we can be sure to catch all possibilities for the fix.

**Comment by PWagner1** [comment] 2024-09-02 17:38
@giduac 

Correct me if this is wrong, but I've added:

```cs
case PaletteState.ContextNormal:
                            return PaletteRibbonColorStyle.RibbonGroupAreaBorderContext;
```

**Comment by DigitalMills** [comment] 2024-09-03 15:42
@PWagner1 

Unfortunately I can't get a breakpoint on GetRibbonBackColorStyle method to confirm the style and the state, hopefully the above will suffice.

The application is rendering a new form when the issue occurs.

> @giduac
> 
> Correct me if this is wrong, but I've added:
> 
> ```cs
> case PaletteState.ContextNormal:
>                             return PaletteRibbonColorStyle.RibbonGroupAreaBorderContext;
> ```

Do let me I'm happy to test any builds

**Comment by giduac** [comment] 2024-09-03 16:14
@PWagner1 

These 5 states need checking:

```cs
  PaletteState.ContextPressed
  PaletteState.ContextTracking
  PaletteState.ContextCheckedTracking
  PaletteState.ContextNormal
  PaletteState.ContextCheckedNormal
```

The error is present in ALL themes and can be provoked by setting the ContextName property: `KRibbon.SelectedTab.ContextName`

Before making any changes make sure to reproduce the error...

**Comment by PWagner1** [comment] 2024-09-07 07:10
Hi @giduac & @DigitalMills 

I don't quite understand what's going on. If you use the `Ribbon + Navigator + Workspace` demo, it works as expected, yet if you try to do it yourself, it ends up with showing the said dialog. There are no structural changes between V90 & V4.

cc. @Smurf-IV

**Comment by giduac** [comment] 2024-09-07 07:38
> Hi @giduac & @DigitalMills
> 
> I don't quite understand what's going on. If you use the `Ribbon + Navigator + Workspace` demo, it works as expected, yet if you try to do it yourself, it ends up with showing the said dialog. There are no structural changes between V90 & V4.
> 
> cc. @Smurf-IV

I also get the error in Workspace Navigator test form:


https://github.com/user-attachments/assets/ac570a59-91d2-411e-b0b7-55e19bc6a408

**Comment by giduac** [comment] 2024-09-07 07:40
Also happens when no context is created and only the ContextName property is set.

**Comment by PWagner1** [comment] 2024-09-07 07:44
> > Hi @giduac & @DigitalMills
> > I don't quite understand what's going on. If you use the `Ribbon + Navigator + Workspace` demo, it works as expected, yet if you try to do it yourself, it ends up with showing the said dialog. There are no structural changes between V90 & V4.
> > cc. @Smurf-IV
> 
> I also get the error in Workspace Navigator test form:
> 
>  devenv_vQ2PUdeg2u.mp4

@giduac 

Would you mind testing on the changes I've recently pushed, using the `Ribbon` test, as it's a clone of the `Ribbon + Navigator + Workspace` demo app? Thanks :)

**Comment by giduac** [comment] 2024-09-07 07:46
My branch is up-to-date until:

![image](https://github.com/user-attachments/assets/0e0f45e4-e811-473c-9273-0aea84923ddd)
 
Is that correct ?

**Comment by PWagner1** [comment] 2024-09-07 07:48
I don't think this has anything to do with themes per se, rather this is a fundamental `Ribbon` issue.

**Comment by PWagner1** [comment] 2024-09-07 07:50
> My branch is up-to-date until:
> 
> ![image](https://private-user-images.githubusercontent.com/96108132/365351855-0e0f45e4-e811-473c-9273-0aea84923ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2OTU2NDcsIm5iZiI6MTcyNTY5NTM0NywicGF0aCI6Ii85NjEwODEzMi8zNjUzNTE4NTUtMGUwZjQ1ZTQtZTgxMS00NzNjLTkyNzMtMGFlYTg0OTIzZGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA3NDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1OWUxNGY3MjJmZjcyNTg5MDRiZGVjOTc1MTc2NjZlMmQ3NmE4Mzk3MzE3YjJkZDAxNWZjZmFlOTI1OTlkNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RVp7aKBxCGLh7jTCR87HKUQh3_x-kPeRS6LrmqCdygo)
> 
> Is that correct ?

@giduac 

Here's the [branch](https://github.com/Krypton-Suite/Standard-Toolkit/tree/1715-bug-90247204-beta-not-implemented-exception-thrown-for-getribbonbackcolorstyle-paletteoffice2010basecs-v90)

**Comment by giduac** [comment] 2024-09-07 07:52
Our branches are on par...
I'm my own local branch here. Where there have been no corrections and there is still present on all levels.

> I don't think this has anything to do with themes per se, rather this is a fundamental `Ribbon` issue.

The error ends up in theme code where those styles are missing.
So it's either that or who put those styles in the ribbon ???

**Comment by PWagner1** [comment] 2024-09-07 07:57
> Our branches are on par... I have my own local branch here. Where there have been no corrections and the error is still present on all levels.
> 
> > I don't think this has anything to do with themes per se, rather this is a fundamental `Ribbon` issue.
> 
> The error ends up in theme code where those styles are missing. So it's either that or who put those styles in the ribbon ???

If you do a diff comparison on the same block of code on V90 and V4 by CF, there are no changes in the case statements being used, which makes it even more odd.

**Comment by giduac** [comment] 2024-09-07 08:13
The one who added those states to the ribbon didn't update the themes with those styles, I would say.
So if you want to get to the bottom of that will be possible starting point.

For the fix:
If you change the ribbon it will possibly be a breaking change.
So my choice would be to add the styles to the themes...

**Comment by PWagner1** [comment] 2024-09-07 08:18
> So my choice would be to add the styles to the themes...

Do you mean adding new `PaletteRibbonColorStyle` definitions?

**Comment by giduac** [comment] 2024-09-07 08:19
No the missing case styles that come up now in the error.
Those are the things that are missing or not ?

**Comment by PWagner1** [comment] 2024-09-07 08:26
> No the missing case styles that come up now in the error. Those are the things that are missing or not ?

Ahh adding the missing cases, might be better to add all of them. Yes the `switch` might be big, but we would cover all eventualities.

**Comment by giduac** [comment] 2024-09-07 08:28
Not all of those I listed are triggered in the error but also not present.
So it makes sense imo to check all those states and see if they should be part of the fix

**Comment by giduac** [comment] 2024-09-07 08:29
Once that has been established a standard fix for all themes can be devised.

**Comment by PWagner1** [comment] 2024-09-07 09:08
@giduac 

Hold on... could it be because `KRibbon.SelectedTab` might be `null`?

**Comment by giduac** [comment] 2024-09-07 09:14
if selectedtab is null could the contextname be set and the case be triggered?

**Comment by PWagner1** [comment] 2024-09-07 09:19
![image](https://github.com/user-attachments/assets/b8b9651e-88a7-4745-898c-f538ade09cc4)

**Comment by giduac** [comment] 2024-09-07 09:21
> if selectedtab is null could the contextname be set and the case be triggered?

@PWagner1 
well ?

**Comment by PWagner1** [comment] 2024-09-07 09:24
> > if selectedtab is null could the contextname be set and the case be triggered?
> 
> @PWagner1 well ?

@giduac 

Just trying something...

**Comment by PWagner1** [comment] 2024-09-07 09:27
@giduac & @giduac 

Yes!!!! It's now fixed!

All it required was...

![image](https://github.com/user-attachments/assets/06b1fa77-ec1a-4f3e-bcee-e30b2b976eac)

PR coming soon

**Comment by giduac** [comment] 2024-09-07 09:29
You sure that all the states should react the same ?

**Comment by PWagner1** [comment] 2024-09-07 09:32
> You sure that all the states should react the same ?

No, that will be the second part. For now, let's deal with the crux of the bug, then add the colour states :)

**Comment by giduac** [comment] 2024-09-07 09:34
Oh, those can differ among the themes, yes ?

**Comment by giduac** [comment] 2024-09-07 09:37
also, like in PaletteOffice2010Base some of these context styles are already addressed. Like `ContextCheckedNormal` here...

```cs
    case PaletteRibbonBackStyle.RibbonGroupArea:
        switch (state)
        {
            case PaletteState.Normal:
            case PaletteState.CheckedNormal:
                return PaletteRibbonColorStyle.RibbonGroupAreaBorder3;
            case PaletteState.ContextCheckedNormal:
                return PaletteRibbonColorStyle.RibbonGroupAreaBorder4;
            case PaletteState.Tracking:
                return PaletteRibbonColorStyle.RibbonGroupNormalTrackingLight;
            case PaletteState.FocusOverride:
                return PaletteRibbonColorStyle.RibbonTabFocus2010;
            default:
                // Should never happen!
                Debug.Assert(false);
                DebugTools.NotImplemented(state.ToString());
                break;
        }
```

**Comment by PWagner1** [comment] 2024-09-07 09:39
> Oh, those can differ among the themes, yes ?

Yes, as the statements can be rearranged. For now, I'm just setting a default for them, it might not look pretty but at least it wont crash applications.

**Comment by giduac** [comment] 2024-09-07 09:41
Should finish the rest straight after that ???

**Comment by giduac** [comment] 2024-09-07 09:41
and make it whole

**Comment by giduac** [comment] 2024-09-07 09:44
can I work on 1241 now ?

**Comment by giduac** [comment] 2024-09-07 09:44
;)

**Comment by PWagner1** [comment] 2024-09-07 09:46
> Should finish the rest straight after that ???

The statements will be moved into position once we know it's working

> can I work on 1241 now ?

Yes, go ahead :)

**Comment by PWagner1** [comment] 2024-09-08 07:00
Hi @DigitalMills 

Please try using the next `nightly` build.

**Comment by PWagner1** [comment] 2024-09-09 13:59
Hi @DigitalMills 

Please retry using `nightly` build >= .253

cc. @Smurf-IV & @giduac

**Comment by DigitalMills** [comment] 2024-09-09 14:43
@PWagner1 looking good for us now on build .253, much appreciated!

Unfortunately we are still experiencing [https://github.com/Krypton-Suite/Standard-Toolkit/issues/1714](this issue) though, can you take a look and address this one too?

Thanks,

**Comment by PWagner1** [comment] 2024-09-09 14:46
> @PWagner1 looking good for us now on build .253, much appreciated!
> 
> Unfortunately we are still experiencing [this issue](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1714) though, can you take a look and address this one too?
> 
> Thanks,

@DigitalMills 

Yes, but I'm really busy with other work this week. Good to see that it's fixed.

**Closed by PWagner1** 2024-09-09 14:46 UTC
Labels: bug, area:themes, area:ribbon, awaiting feedback, version:85, version:90

**Comment by DigitalMills** [comment] 2024-09-09 14:49
No problem @PWagner1, if this can be given some priority when possible as we hope to build upon this for our next release, and tis will be the final obstacle. thank you
