### ISSUE TITLE
[Bug]: Minimize icon in form titlebar is not disabled

### ISSUE THREAD

**Issue by neumatho** [Krypton-Suite/Standard-Toolkit#51] opened 2021-03-06 12:26 UTC
If you have a windows form derived from KryptonForm and the MinimizeBox and ShowInTaskBar properties are set to false on the Form (in designer), then the minimize button is not disabled. It is not possible to click on it, but I expect it to be disabled as well (greyed out).

If you from the normal .NET Form class instead, it is working as expected.

I'm using the .NET 5 framework.

-Thomas

**Comment by Wagnerp** [comment] 2021-03-10 12:42
Hi @neumatho 

Is this working with a normal form?

**Comment by neumatho** [comment] 2021-03-10 12:43
Yes, if you just derive from Form instead of KryptonForm, then it works.

**Comment by Wagnerp** [comment] 2021-03-11 08:18
Hi @neumatho 

Did this occur in previous versions?

**Comment by neumatho** [comment] 2021-03-11 14:54
I have only tried in the last two releases (5.550.2101and 5.550.2103), because this where I started to use this library, so I don't know. Also note that I use the krypton.toolkit.lite versions of the library and using .NET 5.

**Comment by Wagnerp** [comment] 2021-03-16 15:41
Hi @neumatho 

That's odd, as the `KryptonForm` is a skin over the normal `Form`. Is it possible to test with .NET Framework 4.8?

**Comment by neumatho** [comment] 2021-03-16 16:11
The issues is also with the .NET Framework version. I cannot click on the minimize button, so it is only the visual that is wrong.

It is really simple to reproduce. 

1. Create a new empty WinForms project.
2. Add Krypton.Toolkit.Lite via Nuget.
3. In the form designer, select the form and set MinimizeBox and ShowInTaskBar to false.
4. You can now see in the designer (if running framework version), that the button is disabled. Also when you run the code.
5. Change the Form1.cs file, so it derives from KryptonForm instead of Form.
6. When you run the code, now the minimize button is enabled, but unclickable.

**Comment by Wagnerp** [comment] 2021-03-16 19:19
Hi @neumatho 

I think it was designed that way. Can't remember how it looked on XP.

**Comment by Smurf-IV** [comment] 2021-08-08 06:36
I cannot replicate this in the latest canary - Net4.8 (Going to try .net5 next)
![DisabledMinimizeButton](https://user-images.githubusercontent.com/2418812/128623276-c516b853-2dff-499a-988e-0a2950de7923.gif)

**Comment by Smurf-IV** [comment] 2021-08-08 06:38
.Net5 is the same as .net4.8.
Settings used:
![image](https://user-images.githubusercontent.com/2418812/128623324-4eaaa28b-7586-480b-a17c-c101c9833146.png)

**Comment by neumatho** [comment] 2021-08-08 07:32
I have only tried the stable version. What is the difference between Canary and stable? Do you recommed the Canary version in production code?

**Comment by Smurf-IV** [comment] 2021-08-08 07:45
> 
> 
> I have only tried the stable version. What is the difference between Canary and stable? 

https://github.com/Krypton-Suite/Standard-Toolkit/blob/canary/README.md#version-history

>Do you recommed the Canary version in production code?

Your choice, do you have a good QA / Test team that will excercise al of the UI, hence the "canary" name; but that statement holds for any UI development anyway.

Also
> 6. When you run the code, now the minimize button is enabled, but unclickable.

Did you play with the themes, because I noticed that sometimes the difference is very subtle.

**Comment by neumatho** [comment] 2021-08-08 07:56
> Your choice, do you have a good QA / Test team that will excercise al of the UI, hence the "canary" name; but that statement holds for any UI development anyway.

It is only me and I use Krypton-Suite in a sparetime project. I will try with the Canary version and come back to you with the result.

> Did you play with the themes, because I noticed that sometimes the difference is very subtle.

I have set the GlobalPaletteMode to Office 2010 - Blue in the KryptonManager, that's it.

**Comment by Smurf-IV** [comment] 2021-08-08 08:07
That's one of the themes where the box does not change colour !!
In fact none of the "Office 2010" #### Themes have a colour change for the disabled form elements :-(
@Wagnerp : So that is the "Bug"

**Comment by neumatho** [comment] 2021-08-08 08:10
Great you found it :-)

**Comment by Smurf-IV** [comment] 2021-08-08 08:25
> Great you found it :-)

Thanks for raising the issue, and being patient as "we" go through these bugs and funnies 👍 

Yupe; It's a theme thing, because the `I` postfix is supposed to be the disabled state:
![image](https://user-images.githubusercontent.com/2418812/128625923-bada9207-1e77-4386-9399-96a8f17785b4.png)

**Comment by Smurf-IV** [comment] 2021-08-08 10:24
The "Bug" also applies to all ButtonSpec Icons in Office365 themes as well.

**Comment by Smurf-IV** [comment] 2021-08-21 06:27
@Wagnerp Something to check whilst you are doing the resources revamp.

**Comment by Wagnerp** [comment] 2021-08-21 06:56
@Smurf-IV As I recall, there are no `I` versions post 2007.

**Comment by Smurf-IV** [comment] 2021-08-21 07:00
But there "should" be, as it clearly (As per the investigations into the different Office versions I did) they do / should exist.

**Comment by Wagnerp** [comment] 2021-08-21 07:13
Why aren't they being used? Did something change between the O2k7 & O2k10 code?

**Comment by Smurf-IV** [comment] 2021-08-21 07:16
Just not implemented by whomever created the 2010 code, and then that was maybe used as a template for the oters going forward. See https://github.com/Krypton-Suite/Standard-Toolkit/issues/51#issuecomment-894762357

**Comment by Wagnerp** [comment] 2021-08-21 07:16
The O2k10 images

![image](https://user-images.githubusercontent.com/949607/130314001-d1007d6d-be9b-4938-add0-e2196a8640a8.png)

**Comment by Wagnerp** [comment] 2021-08-21 07:18
Only can find `Normal` & `Hover`, no `Disabled`

**Comment by Smurf-IV** [comment] 2021-08-21 07:20
> 
> 
> Only can find `Normal` & `Hover`, no `Disabled`

Yes, _That's the problem_, and this is then not reflected in the code (Unlike previous themes), and is also propagated to later themes.

**Comment by Wagnerp** [comment] 2021-08-21 07:22
Is it possible to fix using the O2k7 version?

**Comment by Smurf-IV** [comment] 2021-08-21 07:31
The code style for setting the form buttons, will have to changed to match O2k7 for all themes, and then for all themes to have the appropriate disabled icons so that they can be used.
So as part of the resource revamp that you are doing, then include the disabled images for all elements, and then the code can be modified to use them 👍

**Comment by Wagnerp** [comment] 2021-08-21 07:41
Would screen grabs work for the relevant images, think I know what to do in code.

**Comment by Wagnerp** [comment] 2021-08-21 11:29
O2k10 Silver 

![Office2010SilverMinimiseDisabled](https://user-images.githubusercontent.com/949607/130320306-7f422ed9-f1aa-4120-b677-e23cda168988.png)

Black

![Office2010BlackMinimiseDisabled](https://user-images.githubusercontent.com/949607/130320322-46e9881a-f070-4070-bd40-8d02d2fef7e0.png)

Blue

![Office2010BlueMinimiseDisabled](https://user-images.githubusercontent.com/949607/130320333-72c07920-de6e-435d-bfb9-9f07a7871a05.png)

**Comment by Wagnerp** [comment] 2021-08-21 11:44
O2k7:

![image](https://user-images.githubusercontent.com/949607/130320641-4e9e2695-7c41-495f-938a-1e256ffd37c1.png)

O2k10 & up:

![image](https://user-images.githubusercontent.com/949607/130320664-d820b79b-bf79-483d-a624-bd87a3d81009.png)

**Comment by Wagnerp** [comment] 2021-08-21 18:18
@Smurf-IV & @neumatho Is the bug in the sparkle themes as well?

**Comment by Wagnerp** [comment] 2021-08-23 11:31
Fixed in build 2109 (Canary)

**Closed by Wagnerp** 2021-08-23 11:31 UTC
Labels: bug, completed, fixed, themes
