### ISSUE TITLE
[Question]: Splitting title bar upon maximizing the window

### ISSUE THREAD

**Issue by Richardthegreatdev** [Krypton-Suite/Standard-Toolkit#1360] opened 2024-02-29 15:34 UTC
Hi,all
Below is the screenshot of one of the sample applications when the applications just started. It works fine.
![image_normal](https://github.com/Krypton-Suite/Standard-Toolkit/assets/126808092/fd0d23a4-7428-4018-b2d8-f267365f9790)

But when the windows is maximized. The title bar is splited into two as indicated by RED color in left upper corner of the following screenshot. When the size of windows is restored, they merge into one again as  normally in above screenshot. Is there any setting in `Form` class of the Krypton to prevent this?
![image_Issue_marked](https://github.com/Krypton-Suite/Standard-Toolkit/assets/126808092/0653cdb6-fd4b-4330-97fe-1079d7259184)

It also happen in my own app.
Thanks
Richard

**Comment by Wagnerp** [comment] 2024-02-29 16:41
Hi @Richardthegreatdev 

Is this a duplicate of #1188 & #1145?

**Comment by Richardthegreatdev** [comment] 2024-03-02 09:08
Hi @Wagnerp  
Thank for pointing out to issues. It seems to be similar with #1188 except that in 1188, the text moved to center in duplicated title bar while i face is a repeat on the left side. 


The issue is with version version 80.23.11.321 from nuget. and self compiled dll of recent commit 4c38c8492a2290291047e2f668fa17efe8417931 `* V80 Patch 1`

Thanks

**Comment by Smurf-IV** [comment] 2024-03-02 10:55
Appears to be fixed in V9 (Current alpha)

**Closed by Smurf-IV** 2024-03-02 10:55 UTC
Labels: question, regression
