### ISSUE TITLE
[Bug]: Visual Studio crashes when setting NavigatorMode of KryptonNavigator to "Outlook - Full"

### ISSUE THREAD

**Issue by g-hauer** [Krypton-Suite/Standard-Toolkit#1609] opened 2024-07-06 11:33 UTC
**Describe the bug**
Visual Studio crashes when setting NavigatorMode of KryptonNavigator to "Outlook - Full" with the Visual-Studio Form Designer. You can set it within the Form.Designer.cs und the Navigator works as expected when running the compiled exe. But as soon as you change the Mode to Outlook-Full within the UI (or open a form with this navigator mode set), visual studio crashes with an exception "Object reference not set to an instance of an object"

**To Reproduce**
1. Add a new Form to your Project
2. Add Krypton Navigtor to the Form
3. Within the Properties Window, set NavigatorMode to "Outlook - Full"

**Expected behavior**
Visual Studio should not crash and the NavigatorMode "Outlook - Full" should be displayed within the Designer

**Screenshots**
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/101356437/8142af0b-e338-41a3-86fe-050c7bd3ad00)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 10.0.22631.3737
 - Framework/.NET Version: 4.8
 - Toolkit Version: 85.24.6.176

**Additional context**
-

**Comment by g-hauer** [comment] 2024-07-06 11:36
It does work with Toolkit Version 70.22.11.312

**Comment by Wagnerp** [comment] 2024-07-09 07:32
Hi @Smurf-IV 

Duplicate of #1439, #1243, #1580. Can be closed.

**Closed** 2024-07-09 07:37 UTC
Labels: bug, regression, area:designer, area:navigator, version:85, version:90
