### ISSUE TITLE
[Bug]: KryptonForm has "Black Line" under Titlebar when maximised

### ISSUE THREAD

**Issue by mohatchaks** [Krypton-Suite/Standard-Toolkit#1336] opened 2024-02-15 18:44 UTC
my  info:
Canary version 90.24.1.22-beta
visual 2022
.Net framework 4.8
Windows 10
Gtx 960m ( HD Graphics 530 )
i7 6700hq 

hi i get some weird line . 
when i start with maximized it not get any line but when minimize or resize it get some black line on top of the form
here is some ss
also . i just changed the size of the window didn't change anything else

![Capture1](https://github.com/Krypton-Suite/Standard-Toolkit/assets/121371944/ecdd6931-3608-4ce6-9d21-f3a2699eda6d)
![Capture2](https://github.com/Krypton-Suite/Standard-Toolkit/assets/121371944/2d227d4c-2047-4aec-848e-cab1da7aba8b)
![Capture4](https://github.com/Krypton-Suite/Standard-Toolkit/assets/121371944/3dc2a1ef-9e2c-44e2-8da7-3c671598f822)
![Capture5](https://github.com/Krypton-Suite/Standard-Toolkit/assets/121371944/6ed1b556-45b4-4d7d-8d31-d7a9c86ced61)
![Capture6](https://github.com/Krypton-Suite/Standard-Toolkit/assets/121371944/091847ca-08a3-481a-8386-70f1306e393a)
![empty](https://github.com/Krypton-Suite/Standard-Toolkit/assets/121371944/b352b47c-083c-4c5e-aa0d-776125f3c1e4)

**Comment by Smurf-IV** [comment] 2024-03-24 10:18
Unable to reproduce using todays alpha branch and one of the examples :
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/04be6e86-cad5-4362-8402-9d98210da4e2)
- Win 10 22h2
- net48 app
- 
@mohatchaks Can you provide an example of the app you are using please ?

**Comment by Smurf-IV** [comment] 2024-03-24 10:36
I do not get the `line` when resizing, only in Maximised....

**Comment by Smurf-IV** [comment] 2024-03-24 10:41
Also, In the Krypton Form example app Using resize -> Maximised, there are defects all around where the border is supposed to be not there !

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/97c40ff6-a9aa-49b2-b489-26e17c038114)

**Comment by Smurf-IV** [comment] 2024-03-24 10:46
- When Set to none, the app is too big, and can be seen drawing into the next monitor
- Fixed single - 2 pixels
- Fixed 3D - 3 pixels
- Fixed Dialog - 2, band also the Status bar is clipped
- Sizeable - different mess
- Fixed toolbar - 2
-

**Comment by Smurf-IV** [comment] 2024-03-30 10:13
90.23.12.352-alpha - ok

90.24.1.8-alpha - broken

**Comment by Wagnerp** [comment] 2024-03-30 10:18
> 90.23.12.352-alpha - ok
> 
> 90.24.1.8-alpha - broken

[All](https://github.com/Krypton-Suite/Standard-Toolkit/commits/alpha?since=2023-12-18&until=2024-01-08) changes made through those dates

**Comment by Smurf-IV** [comment] 2024-03-30 13:44
Something in this PR:
https://github.com/Krypton-Suite/Standard-Toolkit/commit/9721f192251fccfc9e8c2ec0153211649dd5cfe9

**Comment by Smurf-IV** [comment] 2024-03-30 13:57
Found it..
It's because the default is -1, and then that is used in the calcs...
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/fb5309b8-8d1d-4e7c-9786-cc294b5f3f00)

**Comment by mohatchaks** [comment] 2024-03-31 01:18
hello smurf .  i have tested the new updates 
 in canary version 90.23.12.352-beta everything is ok like u said there is no black lines on the form or some sort of bugs

. but in the version +90.23.12.352 like

 90.24.1.22-beta
still line but now only when maximized   
90.24.1.22-beta

![90 24 1 22-beta](https://github.com/Krypton-Suite/Standard-Toolkit/assets/121371944/2f3a90bf-5a8b-4b45-bb2e-b540c7930170)

90.24.3.85-beta i got black background now xd

![90 24 3 85-beta](https://github.com/Krypton-Suite/Standard-Toolkit/assets/121371944/9fa1e266-74a7-465d-ba09-e8320e92f588)

i tried with .net framework 7.2 and .net core 6

**Comment by Smurf-IV** [comment] 2024-03-31 06:32
> 90.24.1.22-beta still line but now only when maximized 90.24.1.22-beta

Yes.. It will be in every build after `90.24.1.8-alpha` (Including canary's)

> 90.24.3.85-beta i got black background now xd

That was fixed yesterday in alpha (Sat 2024-03-30) so will be in the build

PR for this bug will be in, **when** I have fixed all the scenarios listed above - with the different border options

**Closed** 2024-03-31 09:06 UTC
Labels: bug, completed, regression
