### ISSUE TITLE
[Feature Request]: Panels, add external rounding

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Standard-Toolkit#805] opened 2022-08-23 11:05 UTC
Can we get the option to add external rounding on Krypton Panels
![image](https://user-images.githubusercontent.com/84494183/186142692-0253ece9-a418-477a-becf-bd922b93cb3f.png)

**Comment by Smurf-IV** [comment] 2022-09-25 10:55
Duplicate of #241

**Closed by Smurf-IV** 2022-09-25 10:55 UTC
Labels: enhancement, new feature, suggestion
