### ISSUE TITLE
[Bug]: Duplicate window titles when window maximized

### ISSUE THREAD

**Issue by Kohbach** [Krypton-Suite/Standard-Toolkit#1188] opened 2023-11-20 10:58 UTC
Hello,

We use the Krypton controls (including ribbon) in our project. When the main window is maximized, the window title appears twice. We use the “AllowFormChrome = true” property. If we switch the property "AllowFormChrome = false", the main window reacts somewhat strangely to size changes. With this setting, the double window title is gone, but empty space is inserted between the window title and the ribbon.

Can the double window title be turned off?

![WindowTitle](https://github.com/Krypton-Suite/Standard-Toolkit/assets/42990980/de68bb83-74e5-457c-85b5-47216f549c89)

Best regards, Tino

**Comment by Wagnerp** [comment] 2023-12-18 09:23
Possible duplicate of #1145

**Comment by Smurf-IV** [comment] 2024-01-04 18:40
> Seems to be a bug in latest stable? `net48.zip`

@Wagnerp 
You stated and included examples from V80.### but which are showing the problem ?

**Comment by Wagnerp** [comment] 2024-01-05 08:48
> > Seems to be a bug in latest stable? `net48.zip`
> 
> @Wagnerp You stated and included examples from V80.### but which are showing the problem ?

@Smurf-IV the `Outlook Mail Clone` & other ribbon examples show the bug

![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/949607/a5650896-4248-4462-9c99-746e0b80f6a4)

**Comment by Smurf-IV** [comment] 2024-01-05 09:33
> > @Wagnerp You stated and included examples from V80.### but which are showing the problem ?
> @Smurf-IV the `Outlook Mail Clone` & other ribbon examples show the bug

Oh, The Release (Alpha) build of V80 from 2023-05-21 does not show this: It might help with tracking it down.

**Comment by Smurf-IV** [comment] 2024-03-02 10:02
@Wagnerp I cannot seem to r4eplicate the problem as indicated using the Outlook clone using the StdKit Alpha and the "Fixed" code base for Alpha demos included above ?
Can you give it another try please ?

Or is this to be fixed in V8.0
Note: there is a problem with the designer when trying to open the Outlook Clone form - something to do with deserialisation (Probably something to do with the new strings etc - I'll look into this a bit more)

**Comment by Wagnerp** [comment] 2024-03-02 10:26
> @Wagnerp I cannot seem to r4eplicate the problem as indicated using the Outlook clone using the StdKit Alpha and the "Fixed" code base for Alpha demos included above ? Can you give it another try please ?
> 
> Or is this to be fixed in V8.0 Note: there is a problem with the designer when trying to open the Outlook Clone form - something to do with deserialisation (Probably something to do with the new strings etc - I'll look into this a bit more)

@Smurf-IV Seems to be fixed in V90

**Closed** 2024-03-02 10:54 UTC
Labels: bug, regression
