### ISSUE TITLE
[Bug]: Exception switching certain theme(s) [Alpha]

### ISSUE THREAD

**Issue by tobitege** [Krypton-Suite/Standard-Toolkit#1321] opened 2024-02-07 17:42 UTC
**Bug description**

Open the TestForm application from freshly cloned alpha branch, click Theme and use the theme combobox to select one of the bottom "Microsoft 36 - Black" themes and switch back/forth between them:

```
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Windows.Forms.Label.GetPreferredSizeCore(Size proposedConstraints)
   at System.Windows.Forms.Control.GetPreferredSize(Size proposedSize)
   at System.Windows.Forms.Label.GetPreferredSize(Size proposedSize)
   at System.Windows.Forms.Label.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**To Reproduce**
See above. I can reproduce exception 100% of the times switching between the 2 black themes.
I haven't changed a single property or line of code.

**Expected behavior**
The internal text measure methods probably need some refining to avoid draw context issues with .NET.
See the same exception even more wildly with a Treeview on a form and using a custom palette and then issuing "PopulateFromBase()".

**Screenshots**
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit/assets/10787084/e053bd4c-c321-425b-81c3-ae539fb488a6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version:  23H2 all current updates
 - Framework/.NET Version: 4.8 I think
 - Toolkit Version: current alpha branch freshly cloned+rebuild

**Comment by tobitege** [comment] 2024-02-07 17:47
Weirdly, the "Treeview example" form with its theme combobox does not run into exceptions switching through all of them, up and down.

**Comment by giduac** [comment] 2024-06-13 05:20
Hi @Wagnerp,

Please assign to me.

**Comment by Wagnerp** [comment] 2024-06-13 06:23
@giduac Done

**Comment by giduac** [comment] 2024-06-14 10:47
Hi @tobitege,

In addition to our Discord exchange yesterday:
These problems will be solved through [1507](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1507).

Some more info in the (yet to be merged, PR 1525 underway) changelog:
https://github.com/giduac/Standard-Toolkit/blob/1507-Revise-Theme-Selector-Controls/Documents/Changelog/Changelog.md

**Comment by tobitege** [comment] 2024-06-14 12:43
Great job!!

**Comment by giduac** [comment] 2024-06-17 19:19
@Wagnerp ,
This can e closed as it has been solved through the work on theme selectors.
thanks

**Comment by Wagnerp** [comment] 2024-06-18 06:40
Closing...

**Comment by giduac** [comment] 2024-07-19 06:42
Looks like the culprit has been found.
Will need a closer inspection though.

Also found the Ribbon module has such a exception handler and toolkit. Looks like these two are the same so the question arises if one is sufficient.

Altering the Custom Exceptionhandler routine a bit this stacktrace has been captured while in the designer
- at Krypton.Ribbon.KryptonRibbonGroupComboBox.get_SelectedIndex() in Standard-Toolkit\Source\Krypton Components\Krypton.Ribbon\Group Contents\KryptonRibbonGroupComboBox.cs:line 755
- at Krypton.Ribbon.KryptonRibbonGroupThemeComboBox.KryptonManagerGlobalPaletteChanged(Object sender, EventArgs e) in Standard-Toolkit\Source\Krypton Components\Krypton.Ribbon\Group Contents\KryptonRibbonGroupThemeComboBox.cs:line 106
- at System.EventHandler.Invoke(Object sender, EventArgs e)
- at Krypton.Toolkit.KryptonManager.OnGlobalPaletteChanged(EventArgs e) in Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Toolkit\KryptonManager.cs:line 1062
- at Krypton.Toolkit.KryptonManager.set_GlobalPaletteMode(PaletteMode value) in Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Toolkit\KryptonManager.cs:line 261
- at Krypton.Toolkit.ThemeManager.ApplyGlobalTheme(KryptonManager manager, PaletteMode paletteMode) in Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Rendering\ThemeManager.cs:line 71.

**Comment by giduac** [comment] 2024-07-20 04:50
It only happens at design time. Even with the error at design time the code runs fine outside of VS.
Removed the KryptonManager1 instance from the RibbonTest form.
It seems that the serialization of toolbarImages ApplicationIcon property has to do with it. ToolbarImages will be addressed in another call.

Will create a PR for now and close. But it might reappear again.

**Comment by giduac** [comment] 2024-07-20 05:08
It only happens at design time. Even with the error at design time the code runs fine outside of VS.
It is not caused by the ThemeSelectors.
Removed the KryptonManager1 instance from the RibbonTest form.
It seems that the serialization of toolbarImages ApplicationIcon property has to do with it. ToolbarImages will be addressed in another call.

After updating the alpha branch:
- Make sure to rebuild TestForm
- Close the solution 
- Reopen the solution.
- The error should be gone then.

Will create a PR and close.

**Closed** 2024-07-20 07:29 UTC
Labels: bug, fixed, area:themes
