### ISSUE TITLE
[Bug]: Krypton NavigatorMode When Set to "Outlook-Full" Throws an Exception

### ISSUE THREAD

**Issue by pgaraneta** [Krypton-Suite/Standard-Toolkit#1439] opened 2024-04-28 19:17 UTC
When Krypton Navigator NavigatorMode is set to Outlook-Full at design time, an exception is thrown.

1. Add Navigator in a split panel.
2. Set navigatorMode to "Outlook Full"
3. See error

Expected behavior
Krypton Navigator "Outlook-full" mode should work.

Screenshots:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/85190700/86ebcfa3-d844-4cd4-8fb2-2d102b62a335)

Desktop:
 - OS: [e.g. Windows 11]
 - Version: [e.g. 10.0.22000]
 - Framework/.NET Version:  4.8.1
 - Toolkit Version: 80.24.3.64

**Comment by Wagnerp** [comment] 2024-04-29 06:25
Hi @pgaraneta 

Closing, as this is a duplicate of #1243. Please use `Canary` in the meantime.

**Closed by Wagnerp** 2024-04-29 06:25 UTC
Labels: bug, duplicate
